-- ============================================================
-- Immigration Automation - Database Schema (Oracle 12c+)
-- V1: Initial schema creation
--
-- STALE: this Oracle mirror is NOT used by the running stack (Postgres only)
-- and has NOT been migrated to GUID primary keys. The PostgreSQL schema under
-- ../postgresql is the source of truth (uuid PKs via gen_random_uuid()).
-- Regenerate this mirror before targeting Oracle.
-- ============================================================

-- ======================== TABLES ========================

-- Consultants
CREATE TABLE consultants (
    id                NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY,
    consultant_number VARCHAR2(15)   NOT NULL,
    full_name         VARCHAR2(255)  NOT NULL,
    email             VARCHAR2(255)  NOT NULL,
    phone             VARCHAR2(255),
    license_number    VARCHAR2(255),
    company_name      VARCHAR2(255),
    is_admin          NUMBER(1)      DEFAULT 0 NOT NULL,
    active            NUMBER(1)      DEFAULT 1 NOT NULL,
    mcp_api_key       VARCHAR2(255)  NOT NULL,
    created_at        TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at        TIMESTAMP,
    created_by        VARCHAR2(255),
    updated_by        VARCHAR2(255),
    CONSTRAINT pk_consultants PRIMARY KEY (id),
    CONSTRAINT uk_consultants_number UNIQUE (consultant_number),
    CONSTRAINT uk_consultants_email UNIQUE (email),
    CONSTRAINT uk_consultants_mcp_key UNIQUE (mcp_api_key)
);

-- Clients
CREATE TABLE clients (
    id                       NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY,
    client_number            VARCHAR2(15)   NOT NULL,
    full_name                VARCHAR2(255)  NOT NULL,
    email                    VARCHAR2(255)  NOT NULL,
    phone                    VARCHAR2(255),
    whatsapp                 VARCHAR2(255),
    date_of_birth            DATE,
    country_of_citizenship   VARCHAR2(255),
    current_location         VARCHAR2(255),
    current_status           VARCHAR2(255),
    passport_number          VARCHAR2(255),
    marital_status           VARCHAR2(255),
    preferred_language       VARCHAR2(255),
    notes                    CLOB,
    consultant_id            NUMBER(19)     NOT NULL,
    created_at               TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at               TIMESTAMP,
    created_by               VARCHAR2(255),
    updated_by               VARCHAR2(255),
    CONSTRAINT pk_clients PRIMARY KEY (id),
    CONSTRAINT uk_clients_number UNIQUE (client_number),
    CONSTRAINT uk_clients_email UNIQUE (email),
    CONSTRAINT uk_client_name_dob_email UNIQUE (full_name, date_of_birth, email),
    CONSTRAINT fk_clients_consultant FOREIGN KEY (consultant_id) REFERENCES consultants (id)
);

-- Immigration Cases
CREATE TABLE immigration_cases (
    id                        NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY,
    case_number               VARCHAR2(15)   NOT NULL,
    service_type              VARCHAR2(50)   NOT NULL,
    subtype                   VARCHAR2(50),
    applicant_role            VARCHAR2(50),
    lead_status               VARCHAR2(50)   NOT NULL,
    case_status               VARCHAR2(50)   NOT NULL,
    client_id                 NUMBER(19)     NOT NULL,
    consultant_id             NUMBER(19)     NOT NULL,
    intake_summary            CLOB,
    consultant_notes          CLOB,
    deadline                  DATE,
    urgency_reason            VARCHAR2(255),
    submission_date           DATE,
    application_number        VARCHAR2(255),
    portal_used               VARCHAR2(255),
    biometrics_status         VARCHAR2(255),
    medical_status            VARCHAR2(255),
    retainer_signed_date      DATE,
    retainer_document_path    VARCHAR2(255),
    engagement_letter_status  VARCHAR2(255),
    final_reviewed_by         VARCHAR2(255),
    final_reviewed_at         TIMESTAMP,
    final_review_notes        CLOB,
    consultant_signed_off     NUMBER(1)      DEFAULT 0 NOT NULL,
    created_at                TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at                TIMESTAMP,
    created_by                VARCHAR2(255),
    updated_by                VARCHAR2(255),
    CONSTRAINT pk_immigration_cases PRIMARY KEY (id),
    CONSTRAINT uk_cases_number UNIQUE (case_number),
    CONSTRAINT fk_cases_client FOREIGN KEY (client_id) REFERENCES clients (id),
    CONSTRAINT fk_cases_consultant FOREIGN KEY (consultant_id) REFERENCES consultants (id)
);

-- Documents
CREATE TABLE documents (
    id                    NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY,
    case_id               NUMBER(19)     NOT NULL,
    original_file_name    VARCHAR2(255)  NOT NULL,
    stored_file_name      VARCHAR2(255)  NOT NULL,
    file_path             VARCHAR2(255)  NOT NULL,
    mime_type             VARCHAR2(255),
    file_size_bytes       NUMBER(19),
    document_category     VARCHAR2(255),
    document_type         VARCHAR2(255),
    status                VARCHAR2(50)   NOT NULL,
    expiry_date           DATE,
    review_note           CLOB,
    rejection_reason      CLOB,
    translation_required  NUMBER(1)      DEFAULT 0 NOT NULL,
    notarization_required NUMBER(1)      DEFAULT 0 NOT NULL,
    standardized_name     VARCHAR2(255),
    created_at            TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at            TIMESTAMP,
    created_by            VARCHAR2(255),
    updated_by            VARCHAR2(255),
    CONSTRAINT pk_documents PRIMARY KEY (id),
    CONSTRAINT fk_documents_case FOREIGN KEY (case_id) REFERENCES immigration_cases (id)
);

-- Checklist Items
CREATE TABLE checklist_items (
    id                       NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY,
    case_id                  NUMBER(19)     NOT NULL,
    category                 VARCHAR2(255)  NOT NULL,
    document_name            VARCHAR2(255)  NOT NULL,
    description              CLOB,
    status                   VARCHAR2(50)   NOT NULL,
    required                 NUMBER(1)      DEFAULT 1 NOT NULL,
    conditional              NUMBER(1)      DEFAULT 0 NOT NULL,
    condition_description    VARCHAR2(255),
    sort_order               NUMBER(10)     DEFAULT 0 NOT NULL,
    consultant_review_note   CLOB,
    assigned_party           VARCHAR2(255),
    document_id              NUMBER(19),
    created_at               TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at               TIMESTAMP,
    created_by               VARCHAR2(255),
    updated_by               VARCHAR2(255),
    CONSTRAINT pk_checklist_items PRIMARY KEY (id),
    CONSTRAINT fk_checklist_items_case FOREIGN KEY (case_id) REFERENCES immigration_cases (id),
    CONSTRAINT fk_checklist_items_doc FOREIGN KEY (document_id) REFERENCES documents (id)
);

-- Checklist Templates
CREATE TABLE checklist_templates (
    id                          NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY,
    service_type                VARCHAR2(50)   NOT NULL,
    category                    VARCHAR2(255)  NOT NULL,
    document_name               VARCHAR2(255)  NOT NULL,
    description                 CLOB,
    required                    NUMBER(1)      DEFAULT 1 NOT NULL,
    conditional                 NUMBER(1)      DEFAULT 0 NOT NULL,
    condition_description       VARCHAR2(255),
    sort_order                  NUMBER(10)     DEFAULT 0 NOT NULL,
    source_url                  CLOB,
    last_reviewed_date          DATE,
    reviewed_by_consultant_id   NUMBER(19),
    reviewed_by_consultant_name VARCHAR2(255),
    rule_version                NUMBER(10)     DEFAULT 1 NOT NULL,
    approved_for_use            NUMBER(1)      DEFAULT 0 NOT NULL,
    approved_by_consultant_id   NUMBER(19),
    approved_by_consultant_name VARCHAR2(255),
    approved_date               DATE,
    created_at                  TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at                  TIMESTAMP,
    created_by                  VARCHAR2(255),
    updated_by                  VARCHAR2(255),
    CONSTRAINT pk_checklist_templates PRIMARY KEY (id)
);

-- Intake Question Templates
CREATE TABLE intake_question_templates (
    id                  NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY,
    service_type        VARCHAR2(50)   NOT NULL,
    section_name        VARCHAR2(255)  NOT NULL,
    question_key        VARCHAR2(255)  NOT NULL,
    question_label      VARCHAR2(255)  NOT NULL,
    help_text           CLOB,
    input_type          VARCHAR2(50)   NOT NULL,
    options             CLOB,
    required            NUMBER(1)      DEFAULT 0 NOT NULL,
    is_trigger_question NUMBER(1)      DEFAULT 0 NOT NULL,
    sort_order          NUMBER(10)     DEFAULT 0 NOT NULL,
    created_at          TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at          TIMESTAMP,
    created_by          VARCHAR2(255),
    updated_by          VARCHAR2(255),
    CONSTRAINT pk_intake_question_tmpl PRIMARY KEY (id)
);

-- Intake Responses
CREATE TABLE intake_responses (
    id                 NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY,
    case_id            NUMBER(19)     NOT NULL,
    section_name       VARCHAR2(255)  NOT NULL,
    question_key       VARCHAR2(255)  NOT NULL,
    question_label     VARCHAR2(255)  NOT NULL,
    answer             CLOB,
    sort_order         NUMBER(10)     DEFAULT 0 NOT NULL,
    flagged_for_review NUMBER(1)      DEFAULT 0 NOT NULL,
    created_at         TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at         TIMESTAMP,
    created_by         VARCHAR2(255),
    updated_by         VARCHAR2(255),
    CONSTRAINT pk_intake_responses PRIMARY KEY (id),
    CONSTRAINT fk_intake_responses_case FOREIGN KEY (case_id) REFERENCES immigration_cases (id)
);

-- Reminders
CREATE TABLE reminders (
    id            NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY,
    case_id       NUMBER(19)     NOT NULL,
    subject       VARCHAR2(255)  NOT NULL,
    message_body  CLOB           NOT NULL,
    channel       VARCHAR2(50)   NOT NULL,
    status        VARCHAR2(50)   NOT NULL,
    scheduled_at  TIMESTAMP,
    sent_at       TIMESTAMP,
    approved_at   TIMESTAMP,
    approved_by   VARCHAR2(255),
    attempt_count NUMBER(10)     DEFAULT 0 NOT NULL,
    created_at    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at    TIMESTAMP,
    created_by    VARCHAR2(255),
    updated_by    VARCHAR2(255),
    CONSTRAINT pk_reminders PRIMARY KEY (id),
    CONSTRAINT fk_reminders_case FOREIGN KEY (case_id) REFERENCES immigration_cases (id)
);

-- Audit Logs
CREATE TABLE audit_logs (
    id           NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY,
    entity_type  VARCHAR2(255)  NOT NULL,
    entity_id    NUMBER(19)     NOT NULL,
    action       VARCHAR2(255)  NOT NULL,
    details      CLOB,
    performed_by VARCHAR2(255),
    performed_at TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_audit_logs PRIMARY KEY (id)
);

-- Conditional Rules
CREATE TABLE conditional_rules (
    id                           NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY,
    service_type                 VARCHAR2(50)   NOT NULL,
    trigger_question_key         VARCHAR2(255)  NOT NULL,
    trigger_value                VARCHAR2(255)  NOT NULL,
    operator                     VARCHAR2(50)   NOT NULL,
    action_type                  VARCHAR2(50)   NOT NULL,
    target_checklist_template_id NUMBER(19),
    target_question_key          VARCHAR2(255),
    description                  CLOB,
    active                       NUMBER(1)      DEFAULT 1 NOT NULL,
    created_at                   TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at                   TIMESTAMP,
    created_by                   VARCHAR2(255),
    updated_by                   VARCHAR2(255),
    CONSTRAINT pk_conditional_rules PRIMARY KEY (id)
);

-- Party Profiles
CREATE TABLE party_profiles (
    id             NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY,
    case_id        NUMBER(19)     NOT NULL,
    party_type     VARCHAR2(50)   NOT NULL,
    full_name      VARCHAR2(255)  NOT NULL,
    email          VARCHAR2(255),
    phone          VARCHAR2(255),
    relationship   VARCHAR2(255),
    organization   VARCHAR2(255),
    access_token   VARCHAR2(255),
    portal_enabled NUMBER(1)      DEFAULT 0 NOT NULL,
    notes          CLOB,
    created_at     TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at     TIMESTAMP,
    created_by     VARCHAR2(255),
    updated_by     VARCHAR2(255),
    CONSTRAINT pk_party_profiles PRIMARY KEY (id),
    CONSTRAINT fk_party_profiles_case FOREIGN KEY (case_id) REFERENCES immigration_cases (id)
);

-- Travel History Entries
CREATE TABLE travel_history_entries (
    id          NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY,
    case_id     NUMBER(19)     NOT NULL,
    country     VARCHAR2(255)  NOT NULL,
    entry_date  DATE           NOT NULL,
    exit_date   DATE,
    purpose     VARCHAR2(255),
    days_absent NUMBER(10)     DEFAULT 0 NOT NULL,
    notes       CLOB,
    sort_order  NUMBER(10)     DEFAULT 0 NOT NULL,
    created_at  TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at  TIMESTAMP,
    created_by  VARCHAR2(255),
    updated_by  VARCHAR2(255),
    CONSTRAINT pk_travel_history PRIMARY KEY (id),
    CONSTRAINT fk_travel_history_case FOREIGN KEY (case_id) REFERENCES immigration_cases (id)
);

-- Work History Entries
CREATE TABLE work_history_entries (
    id                         NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY,
    case_id                    NUMBER(19)     NOT NULL,
    employer_name              VARCHAR2(255)  NOT NULL,
    job_title                  VARCHAR2(255),
    noc_teer_code              VARCHAR2(255),
    start_date                 DATE           NOT NULL,
    end_date                   DATE,
    current_job                NUMBER(1)      DEFAULT 0 NOT NULL,
    hours_per_week             BINARY_DOUBLE  DEFAULT 0 NOT NULL,
    employment_type            VARCHAR2(50),
    duties                     CLOB,
    country                    VARCHAR2(255),
    city                       VARCHAR2(255),
    reference_letter_received  NUMBER(1)      DEFAULT 0 NOT NULL,
    reference_dates_match      NUMBER(1)      DEFAULT 0 NOT NULL,
    reference_duties_described NUMBER(1)      DEFAULT 0 NOT NULL,
    sort_order                 NUMBER(10)     DEFAULT 0 NOT NULL,
    created_at                 TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at                 TIMESTAMP,
    created_by                 VARCHAR2(255),
    updated_by                 VARCHAR2(255),
    CONSTRAINT pk_work_history PRIMARY KEY (id),
    CONSTRAINT fk_work_history_case FOREIGN KEY (case_id) REFERENCES immigration_cases (id)
);

-- Relationship Timeline Entries
CREATE TABLE relationship_timeline_entries (
    id                NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY,
    case_id           NUMBER(19)     NOT NULL,
    milestone_type    VARCHAR2(255)  NOT NULL,
    milestone_date    DATE           NOT NULL,
    location          VARCHAR2(255),
    description       CLOB,
    evidence_category VARCHAR2(255),
    evidence_count    NUMBER(10)     DEFAULT 0 NOT NULL,
    sort_order        NUMBER(10)     DEFAULT 0 NOT NULL,
    created_at        TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at        TIMESTAMP,
    created_by        VARCHAR2(255),
    updated_by        VARCHAR2(255),
    CONSTRAINT pk_relationship_timeline PRIMARY KEY (id),
    CONSTRAINT fk_rel_timeline_case FOREIGN KEY (case_id) REFERENCES immigration_cases (id)
);

-- Recruitment Evidence
CREATE TABLE recruitment_evidence (
    id                   NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY,
    case_id              NUMBER(19)     NOT NULL,
    evidence_type        VARCHAR2(255)  NOT NULL,
    platform             VARCHAR2(255)  NOT NULL,
    posting_date         DATE           NOT NULL,
    expiry_date          DATE,
    days_posted          NUMBER(10)     DEFAULT 0 NOT NULL,
    applicants_received  NUMBER(10)     DEFAULT 0 NOT NULL,
    interviews_conducted NUMBER(10)     DEFAULT 0 NOT NULL,
    non_hire_reasons     CLOB,
    screenshot_attached  NUMBER(1)      DEFAULT 0 NOT NULL,
    notes                CLOB,
    sort_order           NUMBER(10)     DEFAULT 0 NOT NULL,
    created_at           TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at           TIMESTAMP,
    created_by           VARCHAR2(255),
    updated_by           VARCHAR2(255),
    CONSTRAINT pk_recruitment_evidence PRIMARY KEY (id),
    CONSTRAINT fk_recruitment_case FOREIGN KEY (case_id) REFERENCES immigration_cases (id)
);

-- Candidate Comparisons
CREATE TABLE candidate_comparisons (
    id               NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY,
    case_id          NUMBER(19)     NOT NULL,
    candidate_name   VARCHAR2(255)  NOT NULL,
    candidate_type   VARCHAR2(50)   NOT NULL,
    qualifications   VARCHAR2(255),
    years_experience NUMBER(10)     DEFAULT 0 NOT NULL,
    education_level  VARCHAR2(255),
    language_skills  VARCHAR2(255),
    interviewed      NUMBER(1)      DEFAULT 0 NOT NULL,
    interview_notes  CLOB,
    outcome          VARCHAR2(50),
    non_hire_reason  CLOB,
    sort_order       NUMBER(10)     DEFAULT 0 NOT NULL,
    created_at       TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at       TIMESTAMP,
    created_by       VARCHAR2(255),
    updated_by       VARCHAR2(255),
    CONSTRAINT pk_candidate_comparisons PRIMARY KEY (id),
    CONSTRAINT fk_candidate_comp_case FOREIGN KEY (case_id) REFERENCES immigration_cases (id)
);

-- Expiry Alerts
CREATE TABLE expiry_alerts (
    id                    NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY,
    case_id               NUMBER(19)     NOT NULL,
    alert_type            VARCHAR2(255)  NOT NULL,
    document_description  VARCHAR2(255)  NOT NULL,
    expiry_date           DATE           NOT NULL,
    days_until_expiry     NUMBER(10)     DEFAULT 0 NOT NULL,
    severity              VARCHAR2(50)   NOT NULL,
    acknowledged          NUMBER(1)      DEFAULT 0 NOT NULL,
    acknowledged_by       VARCHAR2(255),
    linked_document_id    NUMBER(19),
    created_at            TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at            TIMESTAMP,
    created_by            VARCHAR2(255),
    updated_by            VARCHAR2(255),
    CONSTRAINT pk_expiry_alerts PRIMARY KEY (id),
    CONSTRAINT fk_expiry_alerts_case FOREIGN KEY (case_id) REFERENCES immigration_cases (id)
);

-- ======================== INDEXES ========================

CREATE INDEX idx_clients_consultant ON clients (consultant_id);
CREATE INDEX idx_clients_email ON clients (email);
CREATE INDEX idx_cases_client ON immigration_cases (client_id);
CREATE INDEX idx_cases_consultant ON immigration_cases (consultant_id);
CREATE INDEX idx_cases_status ON immigration_cases (case_status);
CREATE INDEX idx_cases_lead_status ON immigration_cases (lead_status);
CREATE INDEX idx_cases_service_type ON immigration_cases (service_type);
CREATE INDEX idx_documents_case ON documents (case_id);
CREATE INDEX idx_documents_status ON documents (status);
CREATE INDEX idx_checklist_items_case ON checklist_items (case_id);
CREATE INDEX idx_checklist_tmpl_stype ON checklist_templates (service_type);
CREATE INDEX idx_intake_tmpl_stype ON intake_question_templates (service_type);
CREATE INDEX idx_intake_resp_case ON intake_responses (case_id);
CREATE INDEX idx_reminders_case ON reminders (case_id);
CREATE INDEX idx_reminders_status ON reminders (status);
CREATE INDEX idx_audit_logs_entity ON audit_logs (entity_type, entity_id);
CREATE INDEX idx_cond_rules_stype ON conditional_rules (service_type);
CREATE INDEX idx_party_profiles_case ON party_profiles (case_id);
CREATE INDEX idx_travel_hist_case ON travel_history_entries (case_id);
CREATE INDEX idx_work_hist_case ON work_history_entries (case_id);
CREATE INDEX idx_rel_timeline_case ON relationship_timeline_entries (case_id);
CREATE INDEX idx_recruit_evid_case ON recruitment_evidence (case_id);
CREATE INDEX idx_cand_comp_case ON candidate_comparisons (case_id);
CREATE INDEX idx_expiry_alerts_case ON expiry_alerts (case_id);
CREATE INDEX idx_expiry_alerts_date ON expiry_alerts (expiry_date);
CREATE INDEX idx_expiry_alerts_sev ON expiry_alerts (severity);
