-- ============================================================
-- Immigration Automation - Database Schema (PostgreSQL)
-- V1: Initial schema creation
--
-- Primary keys are GUIDs (uuid) generated by the database via
-- gen_random_uuid() (built into PostgreSQL 13+). Human-facing
-- identifiers (consultant_number, client_number, case_number)
-- are STORED generated columns derived from the uuid id.
-- ============================================================

-- ======================== TABLES ========================

-- Consultants
CREATE TABLE consultants (
    id                UUID         NOT NULL DEFAULT gen_random_uuid(),
    consultant_number VARCHAR(15)  GENERATED ALWAYS AS ('CO' || UPPER(SUBSTR(REPLACE(id::text, '-', ''), 1, 13))) STORED,
    full_name         VARCHAR(255) NOT NULL,
    email             VARCHAR(255) NOT NULL,
    phone             VARCHAR(255),
    license_number    VARCHAR(255),
    company_name      VARCHAR(255),
    admin             BOOLEAN      NOT NULL DEFAULT FALSE,
    active            BOOLEAN      NOT NULL DEFAULT TRUE,
    mcp_api_key       VARCHAR(255) NOT NULL,
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP,
    created_by        VARCHAR(255),
    updated_by        VARCHAR(255),
    CONSTRAINT pk_consultants PRIMARY KEY (id),
    CONSTRAINT uk_consultants_consultant_number UNIQUE (consultant_number),
    CONSTRAINT uk_consultants_email UNIQUE (email),
    CONSTRAINT uk_consultants_mcp_api_key UNIQUE (mcp_api_key)
);

-- Clients
CREATE TABLE clients (
    id                       UUID         NOT NULL DEFAULT gen_random_uuid(),
    client_number            VARCHAR(15)  GENERATED ALWAYS AS ('CN' || UPPER(SUBSTR(REPLACE(id::text, '-', ''), 1, 13))) STORED,
    full_name                VARCHAR(255) NOT NULL,
    email                    VARCHAR(255) NOT NULL,
    phone                    VARCHAR(255),
    whatsapp                 VARCHAR(255),
    date_of_birth            DATE,
    country_of_citizenship   VARCHAR(255),
    current_location         VARCHAR(255),
    current_status           VARCHAR(255),
    passport_number          VARCHAR(255),
    marital_status           VARCHAR(255),
    preferred_language       VARCHAR(255),
    notes                    TEXT,
    consultant_id            UUID         NOT NULL,
    created_at               TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP,
    created_by               VARCHAR(255),
    updated_by               VARCHAR(255),
    CONSTRAINT pk_clients PRIMARY KEY (id),
    CONSTRAINT uk_clients_client_number UNIQUE (client_number),
    CONSTRAINT uk_clients_email UNIQUE (email),
    CONSTRAINT uk_client_name_dob_email UNIQUE (full_name, date_of_birth, email),
    CONSTRAINT fk_clients_consultant FOREIGN KEY (consultant_id) REFERENCES consultants (id)
);

-- Immigration Cases
CREATE TABLE immigration_cases (
    id                        UUID         NOT NULL DEFAULT gen_random_uuid(),
    case_number               VARCHAR(15)  GENERATED ALWAYS AS ('CS' || UPPER(SUBSTR(REPLACE(id::text, '-', ''), 1, 13))) STORED,
    service_type              VARCHAR(50)  NOT NULL,
    subtype                   VARCHAR(50),
    applicant_role            VARCHAR(50),
    lead_status               VARCHAR(50)  NOT NULL,
    case_status               VARCHAR(50)  NOT NULL,
    client_id                 UUID         NOT NULL,
    consultant_id             UUID         NOT NULL,
    intake_summary            TEXT,
    consultant_notes          TEXT,
    deadline                  DATE,
    urgency_reason            VARCHAR(255),
    submission_date           DATE,
    application_number        VARCHAR(255),
    portal_used               VARCHAR(255),
    biometrics_status         VARCHAR(255),
    medical_status            VARCHAR(255),
    retainer_signed_date      DATE,
    retainer_document_path    VARCHAR(255),
    engagement_letter_status  VARCHAR(255),
    final_reviewed_by         VARCHAR(255),
    final_reviewed_at         TIMESTAMP,
    final_review_notes        TEXT,
    consultant_signed_off     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at                TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                TIMESTAMP,
    created_by                VARCHAR(255),
    updated_by                VARCHAR(255),
    CONSTRAINT pk_immigration_cases PRIMARY KEY (id),
    CONSTRAINT uk_immigration_cases_case_number UNIQUE (case_number),
    CONSTRAINT fk_cases_client FOREIGN KEY (client_id) REFERENCES clients (id),
    CONSTRAINT fk_cases_consultant FOREIGN KEY (consultant_id) REFERENCES consultants (id)
);

-- Documents
CREATE TABLE documents (
    id                    UUID         NOT NULL DEFAULT gen_random_uuid(),
    case_id               UUID         NOT NULL,
    original_file_name    VARCHAR(255) NOT NULL,
    stored_file_name      VARCHAR(255) NOT NULL,
    file_path             VARCHAR(255) NOT NULL,
    mime_type             VARCHAR(255),
    file_size_bytes       BIGINT,
    document_category     VARCHAR(255),
    document_type         VARCHAR(255),
    status                VARCHAR(50)  NOT NULL,
    expiry_date           DATE,
    review_note           TEXT,
    rejection_reason      TEXT,
    translation_required  BOOLEAN      NOT NULL DEFAULT FALSE,
    notarization_required BOOLEAN      NOT NULL DEFAULT FALSE,
    standardized_name     VARCHAR(255),
    created_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP,
    created_by            VARCHAR(255),
    updated_by            VARCHAR(255),
    CONSTRAINT pk_documents PRIMARY KEY (id),
    CONSTRAINT fk_documents_case FOREIGN KEY (case_id) REFERENCES immigration_cases (id)
);

-- Checklist Items
CREATE TABLE checklist_items (
    id                       UUID         NOT NULL DEFAULT gen_random_uuid(),
    case_id                  UUID         NOT NULL,
    category                 VARCHAR(255) NOT NULL,
    document_name            VARCHAR(255) NOT NULL,
    description              TEXT,
    status                   VARCHAR(50)  NOT NULL,
    required                 BOOLEAN      NOT NULL DEFAULT TRUE,
    conditional              BOOLEAN      NOT NULL DEFAULT FALSE,
    condition_description    VARCHAR(255),
    sort_order               INT          NOT NULL DEFAULT 0,
    consultant_review_note   TEXT,
    assigned_party           VARCHAR(255),
    document_id              UUID,
    created_at               TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP,
    created_by               VARCHAR(255),
    updated_by               VARCHAR(255),
    CONSTRAINT pk_checklist_items PRIMARY KEY (id),
    CONSTRAINT fk_checklist_items_case FOREIGN KEY (case_id) REFERENCES immigration_cases (id),
    CONSTRAINT fk_checklist_items_document FOREIGN KEY (document_id) REFERENCES documents (id)
);

-- Checklist Templates
CREATE TABLE checklist_templates (
    id                          UUID         NOT NULL DEFAULT gen_random_uuid(),
    service_type                VARCHAR(50)  NOT NULL,
    category                    VARCHAR(255) NOT NULL,
    document_name               VARCHAR(255) NOT NULL,
    description                 TEXT,
    required                    BOOLEAN      NOT NULL DEFAULT TRUE,
    conditional                 BOOLEAN      NOT NULL DEFAULT FALSE,
    condition_description       VARCHAR(255),
    sort_order                  INT          NOT NULL DEFAULT 0,
    source_url                  TEXT,
    last_reviewed_date          DATE,
    reviewed_by_consultant_id   UUID,
    reviewed_by_consultant_name VARCHAR(255),
    rule_version                INT          NOT NULL DEFAULT 1,
    approved_for_use            BOOLEAN      NOT NULL DEFAULT FALSE,
    approved_by_consultant_id   UUID,
    approved_by_consultant_name VARCHAR(255),
    approved_date               DATE,
    created_at                  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TIMESTAMP,
    created_by                  VARCHAR(255),
    updated_by                  VARCHAR(255),
    CONSTRAINT pk_checklist_templates PRIMARY KEY (id)
);

-- Intake Question Templates
CREATE TABLE intake_question_templates (
    id                  UUID         NOT NULL DEFAULT gen_random_uuid(),
    service_type        VARCHAR(50)  NOT NULL,
    section_name        VARCHAR(255) NOT NULL,
    question_key        VARCHAR(255) NOT NULL,
    question_label      VARCHAR(255) NOT NULL,
    help_text           TEXT,
    input_type          VARCHAR(50)  NOT NULL,
    options             TEXT,
    required            BOOLEAN      NOT NULL DEFAULT FALSE,
    is_trigger_question BOOLEAN      NOT NULL DEFAULT FALSE,
    sort_order          INT          NOT NULL DEFAULT 0,
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP,
    created_by          VARCHAR(255),
    updated_by          VARCHAR(255),
    CONSTRAINT pk_intake_question_templates PRIMARY KEY (id)
);

-- Intake Responses
CREATE TABLE intake_responses (
    id                 UUID         NOT NULL DEFAULT gen_random_uuid(),
    case_id            UUID         NOT NULL,
    section_name       VARCHAR(255) NOT NULL,
    question_key       VARCHAR(255) NOT NULL,
    question_label     VARCHAR(255) NOT NULL,
    answer             TEXT,
    sort_order         INT          NOT NULL DEFAULT 0,
    flagged_for_review BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP,
    created_by         VARCHAR(255),
    updated_by         VARCHAR(255),
    CONSTRAINT pk_intake_responses PRIMARY KEY (id),
    CONSTRAINT fk_intake_responses_case FOREIGN KEY (case_id) REFERENCES immigration_cases (id)
);

-- Reminders
CREATE TABLE reminders (
    id            UUID         NOT NULL DEFAULT gen_random_uuid(),
    case_id       UUID         NOT NULL,
    subject       VARCHAR(255) NOT NULL,
    message_body  TEXT         NOT NULL,
    channel       VARCHAR(50)  NOT NULL,
    status        VARCHAR(50)  NOT NULL,
    scheduled_at  TIMESTAMP,
    sent_at       TIMESTAMP,
    approved_at   TIMESTAMP,
    approved_by   VARCHAR(255),
    attempt_count INT          NOT NULL DEFAULT 0,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP,
    created_by    VARCHAR(255),
    updated_by    VARCHAR(255),
    CONSTRAINT pk_reminders PRIMARY KEY (id),
    CONSTRAINT fk_reminders_case FOREIGN KEY (case_id) REFERENCES immigration_cases (id)
);

-- Audit Logs (no BaseEntity - has its own timestamp)
CREATE TABLE audit_logs (
    id           UUID         NOT NULL DEFAULT gen_random_uuid(),
    entity_type  VARCHAR(255) NOT NULL,
    entity_id    UUID         NOT NULL,
    action       VARCHAR(255) NOT NULL,
    details      TEXT,
    performed_by VARCHAR(255),
    performed_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_audit_logs PRIMARY KEY (id)
);

-- Conditional Rules
CREATE TABLE conditional_rules (
    id                          UUID         NOT NULL DEFAULT gen_random_uuid(),
    service_type                VARCHAR(50)  NOT NULL,
    trigger_question_key        VARCHAR(255) NOT NULL,
    trigger_value               VARCHAR(255) NOT NULL,
    operator                    VARCHAR(50)  NOT NULL,
    action_type                 VARCHAR(50)  NOT NULL,
    target_checklist_template_id UUID,
    target_question_key         VARCHAR(255),
    description                 TEXT,
    active                      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at                  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TIMESTAMP,
    created_by                  VARCHAR(255),
    updated_by                  VARCHAR(255),
    CONSTRAINT pk_conditional_rules PRIMARY KEY (id)
);

-- Party Profiles
CREATE TABLE party_profiles (
    id             UUID         NOT NULL DEFAULT gen_random_uuid(),
    case_id        UUID         NOT NULL,
    party_type     VARCHAR(50)  NOT NULL,
    full_name      VARCHAR(255) NOT NULL,
    email          VARCHAR(255),
    phone          VARCHAR(255),
    relationship   VARCHAR(255),
    organization   VARCHAR(255),
    access_token   VARCHAR(255),
    portal_enabled BOOLEAN      NOT NULL DEFAULT FALSE,
    notes          TEXT,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP,
    created_by     VARCHAR(255),
    updated_by     VARCHAR(255),
    CONSTRAINT pk_party_profiles PRIMARY KEY (id),
    CONSTRAINT fk_party_profiles_case FOREIGN KEY (case_id) REFERENCES immigration_cases (id)
);

-- Travel History Entries
CREATE TABLE travel_history_entries (
    id          UUID         NOT NULL DEFAULT gen_random_uuid(),
    case_id     UUID         NOT NULL,
    country     VARCHAR(255) NOT NULL,
    entry_date  DATE         NOT NULL,
    exit_date   DATE,
    purpose     VARCHAR(255),
    days_absent INT          NOT NULL DEFAULT 0,
    notes       TEXT,
    sort_order  INT          NOT NULL DEFAULT 0,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP,
    created_by  VARCHAR(255),
    updated_by  VARCHAR(255),
    CONSTRAINT pk_travel_history_entries PRIMARY KEY (id),
    CONSTRAINT fk_travel_history_case FOREIGN KEY (case_id) REFERENCES immigration_cases (id)
);

-- Work History Entries
CREATE TABLE work_history_entries (
    id                        UUID         NOT NULL DEFAULT gen_random_uuid(),
    case_id                   UUID         NOT NULL,
    employer_name             VARCHAR(255) NOT NULL,
    job_title                 VARCHAR(255),
    noc_teer_code             VARCHAR(255),
    start_date                DATE         NOT NULL,
    end_date                  DATE,
    current_job               BOOLEAN      NOT NULL DEFAULT FALSE,
    hours_per_week            DOUBLE PRECISION NOT NULL DEFAULT 0,
    employment_type           VARCHAR(50),
    duties                    TEXT,
    country                   VARCHAR(255),
    city                      VARCHAR(255),
    reference_letter_received BOOLEAN      NOT NULL DEFAULT FALSE,
    reference_dates_match     BOOLEAN      NOT NULL DEFAULT FALSE,
    reference_duties_described BOOLEAN     NOT NULL DEFAULT FALSE,
    sort_order                INT          NOT NULL DEFAULT 0,
    created_at                TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                TIMESTAMP,
    created_by                VARCHAR(255),
    updated_by                VARCHAR(255),
    CONSTRAINT pk_work_history_entries PRIMARY KEY (id),
    CONSTRAINT fk_work_history_case FOREIGN KEY (case_id) REFERENCES immigration_cases (id)
);

-- Relationship Timeline Entries
CREATE TABLE relationship_timeline_entries (
    id                UUID         NOT NULL DEFAULT gen_random_uuid(),
    case_id           UUID         NOT NULL,
    milestone_type    VARCHAR(255) NOT NULL,
    milestone_date    DATE         NOT NULL,
    location          VARCHAR(255),
    description       TEXT,
    evidence_category VARCHAR(255),
    evidence_count    INT          NOT NULL DEFAULT 0,
    sort_order        INT          NOT NULL DEFAULT 0,
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP,
    created_by        VARCHAR(255),
    updated_by        VARCHAR(255),
    CONSTRAINT pk_relationship_timeline_entries PRIMARY KEY (id),
    CONSTRAINT fk_relationship_timeline_case FOREIGN KEY (case_id) REFERENCES immigration_cases (id)
);

-- Recruitment Evidence
CREATE TABLE recruitment_evidence (
    id                   UUID         NOT NULL DEFAULT gen_random_uuid(),
    case_id              UUID         NOT NULL,
    evidence_type        VARCHAR(255) NOT NULL,
    platform             VARCHAR(255) NOT NULL,
    posting_date         DATE         NOT NULL,
    expiry_date          DATE,
    days_posted          INT          NOT NULL DEFAULT 0,
    applicants_received  INT          NOT NULL DEFAULT 0,
    interviews_conducted INT          NOT NULL DEFAULT 0,
    non_hire_reasons     TEXT,
    screenshot_attached  BOOLEAN      NOT NULL DEFAULT FALSE,
    notes                TEXT,
    sort_order           INT          NOT NULL DEFAULT 0,
    created_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP,
    created_by           VARCHAR(255),
    updated_by           VARCHAR(255),
    CONSTRAINT pk_recruitment_evidence PRIMARY KEY (id),
    CONSTRAINT fk_recruitment_evidence_case FOREIGN KEY (case_id) REFERENCES immigration_cases (id)
);

-- Candidate Comparisons
CREATE TABLE candidate_comparisons (
    id               UUID         NOT NULL DEFAULT gen_random_uuid(),
    case_id          UUID         NOT NULL,
    candidate_name   VARCHAR(255) NOT NULL,
    candidate_type   VARCHAR(50)  NOT NULL,
    qualifications   VARCHAR(255),
    years_experience INT          NOT NULL DEFAULT 0,
    education_level  VARCHAR(255),
    language_skills  VARCHAR(255),
    interviewed      BOOLEAN      NOT NULL DEFAULT FALSE,
    interview_notes  TEXT,
    outcome          VARCHAR(50),
    non_hire_reason  TEXT,
    sort_order       INT          NOT NULL DEFAULT 0,
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP,
    created_by       VARCHAR(255),
    updated_by       VARCHAR(255),
    CONSTRAINT pk_candidate_comparisons PRIMARY KEY (id),
    CONSTRAINT fk_candidate_comparisons_case FOREIGN KEY (case_id) REFERENCES immigration_cases (id)
);

-- Expiry Alerts
CREATE TABLE expiry_alerts (
    id                    UUID         NOT NULL DEFAULT gen_random_uuid(),
    case_id               UUID         NOT NULL,
    alert_type            VARCHAR(255) NOT NULL,
    document_description  VARCHAR(255) NOT NULL,
    expiry_date           DATE         NOT NULL,
    days_until_expiry     INT          NOT NULL DEFAULT 0,
    severity              VARCHAR(50)  NOT NULL,
    acknowledged          BOOLEAN      NOT NULL DEFAULT FALSE,
    acknowledged_by       VARCHAR(255),
    linked_document_id    UUID,
    created_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP,
    created_by            VARCHAR(255),
    updated_by            VARCHAR(255),
    CONSTRAINT pk_expiry_alerts PRIMARY KEY (id),
    CONSTRAINT fk_expiry_alerts_case FOREIGN KEY (case_id) REFERENCES immigration_cases (id)
);

-- ======================== INDEXES ========================

CREATE INDEX idx_clients_consultant ON clients (consultant_id);
CREATE INDEX idx_clients_email ON clients (email);
CREATE INDEX idx_cases_client ON immigration_cases (client_id);
CREATE INDEX idx_cases_consultant ON immigration_cases (consultant_id);
CREATE INDEX idx_cases_status ON immigration_cases (case_status);
CREATE INDEX idx_cases_lead_status ON immigration_cases (lead_status);
CREATE INDEX idx_cases_service_type ON immigration_cases (service_type);
CREATE INDEX idx_documents_case ON documents (case_id);
CREATE INDEX idx_documents_status ON documents (status);
CREATE INDEX idx_checklist_items_case ON checklist_items (case_id);
CREATE INDEX idx_checklist_templates_service_type ON checklist_templates (service_type);
CREATE INDEX idx_intake_templates_service_type ON intake_question_templates (service_type);
CREATE INDEX idx_intake_responses_case ON intake_responses (case_id);
CREATE INDEX idx_reminders_case ON reminders (case_id);
CREATE INDEX idx_reminders_status ON reminders (status);
CREATE INDEX idx_audit_logs_entity ON audit_logs (entity_type, entity_id);
CREATE INDEX idx_conditional_rules_service_type ON conditional_rules (service_type);
CREATE INDEX idx_party_profiles_case ON party_profiles (case_id);
CREATE INDEX idx_travel_history_case ON travel_history_entries (case_id);
CREATE INDEX idx_work_history_case ON work_history_entries (case_id);
CREATE INDEX idx_relationship_timeline_case ON relationship_timeline_entries (case_id);
CREATE INDEX idx_recruitment_evidence_case ON recruitment_evidence (case_id);
CREATE INDEX idx_candidate_comparisons_case ON candidate_comparisons (case_id);
CREATE INDEX idx_expiry_alerts_case ON expiry_alerts (case_id);
CREATE INDEX idx_expiry_alerts_expiry ON expiry_alerts (expiry_date);
CREATE INDEX idx_expiry_alerts_severity ON expiry_alerts (severity);
