-- ============================================================
-- Immigration Automation - Seed Data
-- V2: Initial reference data + demo consultant
-- ============================================================

-- ======================== DEMO CONSULTANT ========================

-- id and consultant_number are generated by the database (uuid PK + STORED generated number).
INSERT INTO consultants (full_name, email, license_number, company_name, admin, active, mcp_api_key, created_at)
VALUES ('Demo Consultant', 'demo@immiauto.ca', 'R000000', 'Demo Immigration Services', TRUE, TRUE, 'mcp_demo00000000000000000000000000', CURRENT_TIMESTAMP);

-- ======================== CHECKLIST TEMPLATES ========================

-- ---- Study Permit ----
INSERT INTO checklist_templates (id, service_type, category, document_name, description, required, conditional, condition_description, sort_order, rule_version, approved_for_use, created_at) VALUES
(gen_random_uuid(), 'STUDY_PERMIT', 'Identity', 'Passport biographical page', 'Clear scan of your passport page showing your photo, name, and passport number.', TRUE, FALSE, NULL, 1, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Identity', 'National ID card', 'Front and back of your national identity card, if applicable.', FALSE, FALSE, NULL, 2, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Identity', 'Birth certificate', 'Official birth certificate with English or French translation if needed.', FALSE, FALSE, NULL, 3, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Education', 'Letter of acceptance from DLI', 'Original letter of acceptance from a Designated Learning Institution in Canada.', TRUE, FALSE, NULL, 4, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Education', 'Previous transcripts', 'Academic transcripts from your most recent educational institution.', TRUE, FALSE, NULL, 5, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Education', 'Previous diplomas or degrees', 'Copies of diplomas or degree certificates you have earned.', TRUE, FALSE, NULL, 6, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Attestation', 'Provincial Attestation Letter (PAL/TAL)', 'Attestation letter from the province where your DLI is located.', TRUE, FALSE, NULL, 7, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Attestation', 'Quebec Acceptance Certificate (CAQ)', 'Certificat d''acceptation du Québec, required for Quebec institutions.', TRUE, TRUE, 'Required if school is in Quebec', 8, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Financial', 'Proof of funds - bank statements', 'Bank statements from the last 4 months showing sufficient funds for tuition and living expenses.', TRUE, FALSE, NULL, 9, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Financial', 'Tuition payment receipt', 'Receipt showing tuition has been paid or deposit made to the school.', FALSE, FALSE, NULL, 10, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Financial', 'Scholarship or funding letter', 'Letter confirming scholarship, bursary, or other funding if applicable.', FALSE, FALSE, NULL, 11, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Financial', 'GIC certificate', 'Guaranteed Investment Certificate from a participating financial institution, if applicable.', FALSE, FALSE, NULL, 12, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Financial', 'Sponsor financial documents', 'Bank statements, employment letter, and income proof from your financial sponsor.', FALSE, TRUE, 'Required if a sponsor is providing financial support', 13, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Language', 'Language test results (IELTS/CELPIP/TEF/TCF)', 'Official language test results, if required by the program or for SDS.', FALSE, FALSE, NULL, 14, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Purpose', 'Study plan / statement of purpose', 'Written explanation of why you chose this program and your plans after graduation.', TRUE, FALSE, NULL, 15, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Ties to Home', 'Proof of ties to home country', 'Employment letter, property documents, family obligations, or other evidence of intent to return.', FALSE, FALSE, NULL, 16, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Immigration History', 'Previous visa refusal letter', 'If you have been refused a visa before, provide the refusal letter.', FALSE, FALSE, NULL, 17, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Immigration History', 'Current visa or permit (if in Canada)', 'Copy of current study or work permit, if applying from inside Canada.', FALSE, FALSE, NULL, 18, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Immigration History', 'Previous travel history', 'Copies of previous visas and travel stamps from past international travel.', FALSE, FALSE, NULL, 19, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Civil Status', 'Marriage certificate', 'If married, provide your marriage certificate.', FALSE, FALSE, NULL, 20, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Family', 'Spouse passport and documents', 'Passport and supporting documents for accompanying spouse.', FALSE, TRUE, 'Required if spouse is accompanying', 21, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Family', 'Children birth certificates and passports', 'Birth certificates and passports for accompanying dependent children.', FALSE, TRUE, 'Required if children are accompanying', 22, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Representative', 'Use of Representative form (IMM 5476)', 'Signed form authorizing your immigration consultant to act on your behalf.', TRUE, FALSE, NULL, 23, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Photos', 'Passport-size photos', 'Two recent passport-size photos meeting IRCC specifications.', TRUE, FALSE, NULL, 24, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Country-specific', 'Police clearance certificate', 'Police certificate from your country or any country you lived in for 6+ months since age 18.', FALSE, FALSE, NULL, 25, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Country-specific', 'Medical exam results', 'Results of immigration medical exam, if required based on your country.', FALSE, FALSE, NULL, 26, 1, FALSE, CURRENT_TIMESTAMP);

-- ---- Visitor Visa ----
INSERT INTO checklist_templates (id, service_type, category, document_name, description, required, conditional, condition_description, sort_order, rule_version, approved_for_use, created_at) VALUES
(gen_random_uuid(), 'VISITOR_VISA', 'Identity', 'Passport biographical page', 'Clear scan of your passport showing photo, name, and passport number.', TRUE, FALSE, NULL, 1, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'Identity', 'National ID card', 'Front and back scan of national identity card.', FALSE, FALSE, NULL, 2, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'Financial', 'Bank statements (3 months)', 'Bank statements from the last 3 months showing sufficient funds.', TRUE, FALSE, NULL, 3, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'Financial', 'Employment letter', 'Letter from employer confirming your position, salary, and approved leave.', TRUE, FALSE, NULL, 4, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'Financial', 'Property or asset documents', 'Documents showing property ownership, investments, or other ties to home country.', FALSE, FALSE, NULL, 5, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'Host Documents', 'Host invitation letter', 'Formal letter from host inviting you to Canada, with dates, purpose, and accommodation details.', FALSE, TRUE, 'Required if visiting a host in Canada', 6, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'Host Documents', 'Host proof of status', 'Copy of host''s Canadian citizenship, PR card, or valid immigration status.', FALSE, TRUE, 'Required if visiting a host in Canada', 7, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'Host Documents', 'Host proof of income/finances', 'Host''s employment letter, NOA, or bank statements if host is financially supporting visit.', FALSE, TRUE, 'Required if host is funding the trip', 8, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'Purpose of Visit', 'Travel itinerary', 'Flight booking or travel plan showing intended dates.', FALSE, FALSE, NULL, 9, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'Purpose of Visit', 'Hotel reservations', 'Accommodation booking confirmations.', FALSE, FALSE, NULL, 10, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'Purpose of Visit', 'Business invitation / conference registration', 'Business invitation letter or conference registration for business visitors.', FALSE, TRUE, 'Required for business visitors', 11, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'Purpose of Visit', 'Event tickets or registration', 'Tickets, registration confirmation, or event details.', FALSE, TRUE, 'Required for event visitors', 12, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'Status Documents', 'Current immigration status (if in Canada)', 'Copy of current visa, permit, or visitor record if applying from inside Canada.', FALSE, FALSE, NULL, 13, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'Ties to Home Country', 'Business registration', 'Business registration or ownership documents if self-employed.', FALSE, FALSE, NULL, 14, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'Ties to Home Country', 'Proof of family ties', 'Documents showing family members remaining in your home country.', FALSE, FALSE, NULL, 15, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'Civil Status', 'Marriage certificate', 'If married, provide marriage certificate.', FALSE, FALSE, NULL, 16, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'Civil Status', 'Children birth certificates', 'Birth certificates of dependent children, if applicable.', FALSE, FALSE, NULL, 17, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'Travel History', 'Previous visas and travel stamps', 'Copies of previous visas and passport stamps from past travel.', FALSE, FALSE, NULL, 18, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'Immigration History', 'Previous refusal explanation', 'Written explanation and supporting documents for any prior visa refusals.', FALSE, TRUE, 'Required if previously refused a visa', 19, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'Photos', 'Passport-size photos', 'Two recent passport-size photos meeting IRCC specifications.', TRUE, FALSE, NULL, 20, 1, FALSE, CURRENT_TIMESTAMP);

-- ---- Spousal Sponsorship ----
INSERT INTO checklist_templates (id, service_type, category, document_name, description, required, conditional, condition_description, sort_order, rule_version, approved_for_use, created_at) VALUES
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Identity - Sponsor', 'Sponsor passport', 'Clear scan of sponsor''s Canadian passport or PR card.', TRUE, FALSE, NULL, 1, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Identity - Sponsor', 'Sponsor proof of status', 'PR card, citizenship certificate, or Canadian passport.', TRUE, FALSE, NULL, 2, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Identity - Sponsor', 'Sponsor birth certificate', 'Official birth certificate of the sponsor.', FALSE, FALSE, NULL, 3, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Identity - Applicant', 'Applicant passport', 'Clear scan of applicant''s passport biographical page.', TRUE, FALSE, NULL, 4, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Identity - Applicant', 'Applicant birth certificate', 'Official birth certificate of the applicant.', TRUE, FALSE, NULL, 5, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Relationship', 'Marriage certificate', 'Official marriage certificate.', TRUE, FALSE, NULL, 6, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Relationship', 'Statutory declaration of common-law union', 'Sworn declaration confirming 12+ months of continuous cohabitation.', TRUE, TRUE, 'Required for common-law relationships', 7, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Relationship', 'Relationship timeline narrative', 'Written narrative of how you met, your relationship history, and milestones.', TRUE, FALSE, NULL, 8, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Relationship Evidence - Photos', 'Photos together', 'Photos at different times, with family, at events, in different locations.', TRUE, FALSE, NULL, 9, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Relationship Evidence - Communication', 'Chat/messaging history', 'Screenshots of text messages, WhatsApp, Facebook Messenger, or other messaging apps.', TRUE, FALSE, NULL, 10, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Relationship Evidence - Communication', 'Call logs and video call history', 'Phone call logs and video call screenshots/history.', TRUE, FALSE, NULL, 11, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Relationship Evidence - Travel', 'Travel records together', 'Flight bookings, boarding passes, hotel reservations, or passport stamps from trips together.', FALSE, FALSE, NULL, 12, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Relationship Evidence - Financial', 'Joint bank accounts or shared finances', 'Joint bank account statements or evidence of shared financial responsibilities.', FALSE, FALSE, NULL, 13, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Relationship Evidence - Financial', 'Joint lease, utilities, or insurance', 'Shared lease agreements, utility bills, or insurance policies showing both names.', FALSE, FALSE, NULL, 14, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Relationship Evidence - Third Party', 'Letters from friends and family', 'Sworn affidavits or letters from people who know the relationship.', FALSE, FALSE, NULL, 15, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Financial - Sponsor', 'Tax returns / NOA', 'Notice of Assessment from CRA for the most recent tax year.', TRUE, FALSE, NULL, 16, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Financial - Sponsor', 'Employment letter', 'Letter from sponsor''s employer confirming employment and salary.', FALSE, FALSE, NULL, 17, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Financial - Sponsor', 'Bank statements (3 months)', 'Sponsor''s bank statements for the last 3 months.', FALSE, FALSE, NULL, 18, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Dependents', 'Dependent children birth certificates', 'Birth certificates for all dependent children included in the application.', FALSE, TRUE, 'Required if there are dependent children', 19, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Dependents', 'Custody or adoption documents', 'Court orders, custody agreements, or adoption certificates.', FALSE, TRUE, 'Required if there are custody arrangements', 20, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Quebec', 'Quebec undertaking (CSQ forms)', 'Quebec-specific sponsorship undertaking forms.', FALSE, TRUE, 'Required if sponsor lives in Quebec', 21, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Previous Sponsorship', 'Previous sponsorship proof of completion', 'Proof that 3-year undertaking from a previous sponsorship has ended.', FALSE, TRUE, 'Required if sponsor has sponsored before', 22, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Country-specific', 'Police clearance - applicant', 'Police certificate from applicant''s country and any country lived in 6+ months since age 18.', TRUE, FALSE, NULL, 23, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Country-specific', 'Police clearance - sponsor', 'Police certificate for the sponsor, if applicable.', FALSE, FALSE, NULL, 24, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Country-specific', 'Medical exam results', 'Immigration medical exam results for the applicant and dependents.', TRUE, FALSE, NULL, 25, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Photos', 'Passport-size photos', 'Two recent passport-size photos meeting IRCC specifications.', TRUE, FALSE, NULL, 26, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Representative', 'Use of Representative form (IMM 5476)', 'Signed form authorizing your immigration consultant to act on your behalf.', TRUE, FALSE, NULL, 27, 1, FALSE, CURRENT_TIMESTAMP);

-- ---- Express Entry ----
INSERT INTO checklist_templates (id, service_type, category, document_name, description, required, conditional, condition_description, sort_order, rule_version, approved_for_use, created_at) VALUES
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Identity', 'Passport biographical page', 'Clear scan of passport.', TRUE, FALSE, NULL, 1, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Identity', 'Birth certificate', 'Official birth certificate.', FALSE, FALSE, NULL, 2, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Language', 'Language test results (IELTS/CELPIP/TEF/TCF)', 'Official language test results for primary applicant.', TRUE, FALSE, NULL, 3, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Language', 'Spouse language test results', 'Language test results for accompanying spouse, if applicable.', FALSE, TRUE, 'Required if spouse is accompanying', 4, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Education', 'Canadian transcripts and diplomas', 'Transcripts and diplomas from Canadian educational institutions.', FALSE, FALSE, NULL, 5, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Education', 'Educational Credential Assessment (ECA)', 'WES, IQAS, or other designated ECA report for foreign education.', TRUE, TRUE, 'Required for foreign education credentials', 6, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Education', 'Foreign transcripts and diplomas', 'Transcripts and diplomas from foreign educational institutions.', FALSE, FALSE, NULL, 7, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Work Experience', 'Employment reference letters', 'Detailed reference letters for each qualifying work period: duties, hours, dates, salary.', TRUE, FALSE, NULL, 8, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Work Experience', 'Pay stubs or tax documents', 'Pay stubs, T4s, or equivalent to corroborate employment claims.', FALSE, FALSE, NULL, 9, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Financial', 'Proof of settlement funds', 'Bank statements, investment statements, or GIC showing required funds.', TRUE, FALSE, NULL, 10, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Job Offer', 'Valid job offer letter', 'Signed employment offer from a Canadian employer.', FALSE, TRUE, 'Required if claiming job offer points', 11, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Job Offer', 'LMIA confirmation (if applicable)', 'Labour Market Impact Assessment for the job offer.', FALSE, TRUE, 'Required if job offer requires LMIA', 12, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'PNP', 'Provincial Nomination Certificate', 'Official nomination certificate from a Canadian province or territory.', FALSE, TRUE, 'Required for PNP Express Entry stream', 13, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Police Certificates', 'Police certificate - country of citizenship', 'Police certificate from your country of citizenship.', TRUE, FALSE, NULL, 14, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Police Certificates', 'Police certificate - countries lived 6+ months', 'Police certificates from every country you lived in 6+ months since age 18.', TRUE, FALSE, NULL, 15, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Medical', 'Immigration medical exam (IME)', 'Medical exam from an IRCC-designated panel physician.', TRUE, FALSE, NULL, 16, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Civil Status', 'Marriage certificate or divorce decree', 'Marriage certificate, or divorce/annulment decree if previously married.', FALSE, FALSE, NULL, 17, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Dependents', 'Dependent children documents', 'Birth certificates, passports, and custody documents for dependent children.', FALSE, TRUE, 'Required if including dependents', 18, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Photos', 'Passport-size photos', 'Photos meeting IRCC specifications for applicant and all family members.', TRUE, FALSE, NULL, 19, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Representative', 'Use of Representative form (IMM 5476)', 'Signed form authorizing consultant.', TRUE, FALSE, NULL, 20, 1, FALSE, CURRENT_TIMESTAMP);

-- ---- Work Permit ----
INSERT INTO checklist_templates (id, service_type, category, document_name, description, required, conditional, condition_description, sort_order, rule_version, approved_for_use, created_at) VALUES
(gen_random_uuid(), 'WORK_PERMIT', 'Identity', 'Passport biographical page', 'Clear scan of passport.', TRUE, FALSE, NULL, 1, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'Job/Employer', 'Job offer letter', 'Signed employment offer with title, duties, wage, hours, and location.', TRUE, FALSE, NULL, 2, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'Job/Employer', 'Employer LMIA confirmation', 'Positive LMIA from ESDC, if applicable.', FALSE, FALSE, NULL, 3, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'Job/Employer', 'Employer compliance fee receipt', 'Proof employer paid the compliance fee ($230).', FALSE, FALSE, NULL, 4, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'Job/Employer', 'Employment contract', 'Signed contract with terms and conditions.', TRUE, FALSE, NULL, 5, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'Qualifications', 'Resume / CV', 'Current resume showing relevant experience.', TRUE, FALSE, NULL, 6, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'Qualifications', 'Educational credentials', 'Diplomas, degrees, or certificates relevant to the job.', FALSE, FALSE, NULL, 7, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'Qualifications', 'Professional licence or certification', 'Licence or certification required for the occupation.', FALSE, FALSE, NULL, 8, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'Experience', 'Previous employment reference letters', 'Reference letters from previous employers detailing duties and dates.', FALSE, FALSE, NULL, 9, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'Status', 'Current Canadian status documents', 'Current work permit, study permit, or visitor record.', FALSE, TRUE, 'Required if applying from inside Canada', 10, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'Status', 'Status extension/restoration application', 'Proof of pending status application if status has expired.', FALSE, TRUE, 'Required if current status has expired', 11, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'Family', 'Spouse open work permit documents', 'Spouse passport, marriage certificate, and SOWP application documents.', FALSE, TRUE, 'Required if spouse is applying for open work permit', 12, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'Family', 'Dependent children documents', 'Birth certificates and passports for accompanying children.', FALSE, TRUE, 'Required if children are accompanying', 13, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'Financial', 'Proof of funds for initial settlement', 'Bank statements showing funds for initial period in Canada.', FALSE, FALSE, NULL, 14, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'Photos', 'Passport-size photos', 'Photos meeting IRCC specifications.', TRUE, FALSE, NULL, 15, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'Country-specific', 'Police clearance certificate', 'Police certificate if required based on country.', FALSE, FALSE, NULL, 16, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'Country-specific', 'Medical exam results', 'Immigration medical exam if required.', FALSE, FALSE, NULL, 17, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'Representative', 'Use of Representative form (IMM 5476)', 'Signed form authorizing consultant.', TRUE, FALSE, NULL, 18, 1, FALSE, CURRENT_TIMESTAMP);

-- ---- LMIA ----
INSERT INTO checklist_templates (id, service_type, category, document_name, description, required, conditional, condition_description, sort_order, rule_version, approved_for_use, created_at) VALUES
(gen_random_uuid(), 'LMIA', 'Employer Identity', 'Business licence or registration', 'Provincial or federal business registration documents.', TRUE, FALSE, NULL, 1, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Employer Identity', 'CRA Business Number confirmation', 'Proof of CRA Business Number.', TRUE, FALSE, NULL, 2, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Employer Identity', 'Articles of incorporation', 'Corporate registration or articles of incorporation.', FALSE, FALSE, NULL, 3, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Business Legitimacy', 'T4 Summary (previous year)', 'T4 Summary showing payroll for Canadian employees.', TRUE, FALSE, NULL, 4, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Business Legitimacy', 'Financial statements or tax returns', 'Business financial statements or corporate tax returns.', TRUE, FALSE, NULL, 5, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Business Legitimacy', 'Commercial lease or property proof', 'Proof of business premises.', TRUE, FALSE, NULL, 6, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Business Legitimacy', 'Business insurance', 'Proof of WCB/WSIB or equivalent workplace insurance.', FALSE, FALSE, NULL, 7, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Recruitment', 'Job advertisement screenshots', 'Screenshots of all job ads with dates, platforms, and content.', TRUE, FALSE, NULL, 8, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Recruitment', 'Job Bank posting confirmation', 'Proof of posting on the Government of Canada Job Bank for minimum 4 weeks.', TRUE, FALSE, NULL, 9, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Recruitment', 'Recruitment summary report', 'Summary of number of applicants, interviews conducted, and reasons for non-hire.', TRUE, FALSE, NULL, 10, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Recruitment', 'Interview records', 'Records of interviews conducted with Canadian applicants.', FALSE, FALSE, NULL, 11, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Transition Plan', 'Transition plan document', 'Written plan to reduce reliance on temporary foreign workers.', TRUE, FALSE, NULL, 12, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Provincial', 'Provincial attestation or requirements', 'Province-specific attestation or documentation requirements.', FALSE, TRUE, 'Required by some provinces', 13, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Worker Documents', 'Candidate resume / CV', 'Resume of the foreign worker being hired.', TRUE, FALSE, NULL, 14, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Worker Documents', 'Candidate credentials and qualifications', 'Proof of qualifications relevant to the position.', FALSE, FALSE, NULL, 15, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Fees', 'LMIA processing fee payment receipt ($1,000)', 'Proof of payment of the LMIA processing fee.', TRUE, FALSE, NULL, 16, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Fees', 'Employer compliance fee receipt ($230)', 'Proof of compliance fee payment.', TRUE, FALSE, NULL, 17, 1, FALSE, CURRENT_TIMESTAMP);

-- ---- Citizenship ----
INSERT INTO checklist_templates (id, service_type, category, document_name, description, required, conditional, condition_description, sort_order, rule_version, approved_for_use, created_at) VALUES
(gen_random_uuid(), 'CITIZENSHIP', 'PR Proof', 'PR card (front and back)', 'Clear scan of both sides of current or most recent PR card.', TRUE, FALSE, NULL, 1, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'CITIZENSHIP', 'PR Proof', 'Confirmation of Permanent Residence (COPR)', 'Original COPR or Record of Landing.', TRUE, FALSE, NULL, 2, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'CITIZENSHIP', 'Identity', 'Passport biographical page', 'Current passport biographical page.', TRUE, FALSE, NULL, 3, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'CITIZENSHIP', 'Identity', 'Two passport-size photos', 'Photos meeting IRCC citizenship application specifications.', TRUE, FALSE, NULL, 4, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'CITIZENSHIP', 'Travel History', 'Travel journal / absence log', 'Detailed log of all trips outside Canada during eligibility period with dates and destinations.', TRUE, FALSE, NULL, 5, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'CITIZENSHIP', 'Travel History', 'Passport stamps and boarding passes', 'Evidence supporting declared travel dates.', FALSE, FALSE, NULL, 6, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'CITIZENSHIP', 'Language', 'Language proof (IELTS/CELPIP/TEF/TCF or equivalent)', 'Official language test results or proof of CLB 4+ in English or French.', TRUE, FALSE, NULL, 7, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'CITIZENSHIP', 'Tax Filing', 'Notice of Assessment (NOA) - 3 tax years', 'NOAs from CRA for 3 of the last 5 tax years within eligibility period.', TRUE, FALSE, NULL, 8, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'CITIZENSHIP', 'Tax Filing', 'T1 General tax returns', 'T1 returns corresponding to the NOAs provided.', FALSE, FALSE, NULL, 9, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'CITIZENSHIP', 'Residence', 'Proof of address in Canada', 'Utility bills, lease agreements, or bank statements showing Canadian address.', FALSE, FALSE, NULL, 10, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'CITIZENSHIP', 'Name Change', 'Legal name change certificate', 'Court order or official document showing legal name change.', FALSE, TRUE, 'Required if name has changed since becoming PR', 11, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'CITIZENSHIP', 'Criminal', 'Court records or discharge documents', 'Records of criminal charges, convictions, or absolute/conditional discharge.', FALSE, TRUE, 'Required if applicant has criminal history', 12, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'CITIZENSHIP', 'Minor Applicant', 'Parent/guardian consent and ID', 'Both parents'' ID and signed consent for minor citizenship application.', FALSE, TRUE, 'Required for applicants under 18', 13, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'CITIZENSHIP', 'Representative', 'Use of Representative form', 'Signed form authorizing consultant.', TRUE, FALSE, NULL, 14, 1, FALSE, CURRENT_TIMESTAMP);

-- ---- PR Card / PRTD ----
INSERT INTO checklist_templates (id, service_type, category, document_name, description, required, conditional, condition_description, sort_order, rule_version, approved_for_use, created_at) VALUES
(gen_random_uuid(), 'PR_CARD_PRTD', 'PR Proof', 'Confirmation of Permanent Residence (COPR)', 'Original COPR or Record of Landing.', TRUE, FALSE, NULL, 1, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PR_CARD_PRTD', 'PR Proof', 'Previous PR card (if available)', 'Most recent PR card, even if expired.', FALSE, FALSE, NULL, 2, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PR_CARD_PRTD', 'Identity', 'Passport biographical page', 'Current valid passport.', TRUE, FALSE, NULL, 3, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PR_CARD_PRTD', 'Identity', 'Two passport-size photos', 'Photos meeting IRCC specifications.', TRUE, FALSE, NULL, 4, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PR_CARD_PRTD', 'Residence', 'Proof of Canadian address', 'Utility bill, lease, or government correspondence showing current address.', TRUE, FALSE, NULL, 5, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PR_CARD_PRTD', 'Residence', 'Travel history log (5 years)', 'Detailed log of all absences from Canada in the last 5 years.', TRUE, FALSE, NULL, 6, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PR_CARD_PRTD', 'Residence', 'Passport stamps and travel evidence', 'Supporting evidence for declared travel dates.', FALSE, FALSE, NULL, 7, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PR_CARD_PRTD', 'Lost/Stolen/Damaged', 'Police report', 'Police report or incident number for lost or stolen card.', FALSE, TRUE, 'Required if card was lost or stolen', 8, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PR_CARD_PRTD', 'Lost/Stolen/Damaged', 'Damaged card scan', 'Scan of the damaged card.', FALSE, TRUE, 'Required if card is damaged', 9, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PR_CARD_PRTD', 'Name Change', 'Legal name or gender change documents', 'Court order, marriage certificate, or official change document.', FALSE, TRUE, 'Required if name or gender changed since PR was granted', 10, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PR_CARD_PRTD', 'PRTD', 'Proof of ties to Canada', 'Evidence of home, family, employment, or financial ties to Canada.', FALSE, TRUE, 'Required for PR Travel Document applications', 11, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PR_CARD_PRTD', 'PRTD', 'Explanation of absence from Canada', 'Written explanation for extended absence from Canada.', FALSE, TRUE, 'Required for PRTD when outside Canada', 12, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PR_CARD_PRTD', 'Representative', 'Use of Representative form', 'Signed form authorizing consultant.', TRUE, FALSE, NULL, 13, 1, FALSE, CURRENT_TIMESTAMP);

-- ---- PGWP ----
INSERT INTO checklist_templates (id, service_type, category, document_name, description, required, conditional, condition_description, sort_order, rule_version, approved_for_use, created_at) VALUES
(gen_random_uuid(), 'PGWP', 'Identity', 'Passport biographical page', 'Current valid passport.', TRUE, FALSE, NULL, 1, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PGWP', 'Study Completion', 'Official completion letter from DLI', 'Letter from school confirming program completion and graduation date.', TRUE, FALSE, NULL, 2, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PGWP', 'Study Completion', 'Final transcript', 'Official final transcript showing all courses and grades.', TRUE, FALSE, NULL, 3, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PGWP', 'Study Completion', 'Diploma or degree certificate', 'Copy of diploma or degree, if already issued.', FALSE, FALSE, NULL, 4, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PGWP', 'School/Program', 'Letter of acceptance (original)', 'Original letter of acceptance from the DLI.', FALSE, FALSE, NULL, 5, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PGWP', 'Current Status', 'Current study permit', 'Copy of valid study permit.', TRUE, FALSE, NULL, 6, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PGWP', 'Current Status', 'Implied status proof', 'Proof of implied status if study permit expired but PGWP applied within 90 days.', FALSE, TRUE, 'Required if study permit has expired', 7, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PGWP', 'Language', 'Language test results', 'IELTS, CELPIP, TEF, or TCF results if required for field of study.', FALSE, TRUE, 'Required based on graduation date and program', 8, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PGWP', 'Prior Study', 'Transfer letters from previous institutions', 'Letters from all institutions attended if programs were transferred.', FALSE, TRUE, 'Required if student transferred between programs or schools', 9, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PGWP', 'Photos', 'Passport-size photos', 'Photos meeting IRCC specifications.', TRUE, FALSE, NULL, 10, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PGWP', 'Representative', 'Use of Representative form', 'Signed form authorizing consultant.', TRUE, FALSE, NULL, 11, 1, FALSE, CURRENT_TIMESTAMP);

-- ---- Super Visa ----
INSERT INTO checklist_templates (id, service_type, category, document_name, description, required, conditional, condition_description, sort_order, rule_version, approved_for_use, created_at) VALUES
(gen_random_uuid(), 'SUPER_VISA', 'Identity - Applicant', 'Passport biographical page', 'Applicant''s current valid passport.', TRUE, FALSE, NULL, 1, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SUPER_VISA', 'Relationship', 'Proof of relationship to host', 'Birth certificate, marriage certificate, or other documents proving parent/grandparent relationship.', TRUE, FALSE, NULL, 2, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SUPER_VISA', 'Host Documents', 'Host proof of citizenship or PR', 'Host''s Canadian passport, citizenship certificate, or PR card.', TRUE, FALSE, NULL, 3, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SUPER_VISA', 'Host Documents', 'Host invitation letter', 'Formal invitation letter from host with details of stay.', TRUE, FALSE, NULL, 4, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SUPER_VISA', 'Host Finances', 'Host Notice of Assessment (NOA)', 'CRA Notice of Assessment meeting LICO requirement for household size.', TRUE, FALSE, NULL, 5, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SUPER_VISA', 'Host Finances', 'Host employment letter', 'Letter confirming host''s employment, position, and salary.', TRUE, FALSE, NULL, 6, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SUPER_VISA', 'Host Finances', 'Host bank statements (3 months)', 'Host''s recent bank statements.', FALSE, FALSE, NULL, 7, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SUPER_VISA', 'Medical Insurance', 'Private medical insurance policy', 'Proof of private medical insurance from a Canadian company, valid 1+ year, minimum $100,000 coverage.', TRUE, FALSE, NULL, 8, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SUPER_VISA', 'Medical Insurance', 'Insurance coverage details', 'Policy details showing coverage amount, period, and emergency medical coverage.', TRUE, FALSE, NULL, 9, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SUPER_VISA', 'Medical', 'Immigration medical exam results', 'Medical exam from IRCC-designated panel physician.', TRUE, FALSE, NULL, 10, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SUPER_VISA', 'Travel History', 'Previous visas and travel stamps', 'Copies of previous visas and passport stamps.', FALSE, FALSE, NULL, 11, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SUPER_VISA', 'Immigration History', 'Previous refusal explanation', 'Written explanation for any prior visa refusals.', FALSE, TRUE, 'Required if previously refused a visa', 12, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SUPER_VISA', 'Photos', 'Passport-size photos', 'Photos meeting IRCC specifications.', TRUE, FALSE, NULL, 13, 1, FALSE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SUPER_VISA', 'Representative', 'Use of Representative form', 'Signed form authorizing consultant.', TRUE, FALSE, NULL, 14, 1, FALSE, CURRENT_TIMESTAMP);

-- ======================== INTAKE QUESTION TEMPLATES ========================

-- ---- Study Permit ----
INSERT INTO intake_question_templates (id, service_type, section_name, question_key, question_label, help_text, input_type, options, required, is_trigger_question, sort_order, created_at) VALUES
(gen_random_uuid(), 'STUDY_PERMIT', 'Applicant Identity', 'full_name', 'Full Legal Name (as on passport)', NULL, 'TEXT', NULL, TRUE, FALSE, 1, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Applicant Identity', 'dob', 'Date of Birth', NULL, 'DATE', NULL, TRUE, FALSE, 2, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Applicant Identity', 'citizenship', 'Country of Citizenship', NULL, 'TEXT', NULL, TRUE, FALSE, 3, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Applicant Identity', 'passport_number', 'Passport Number', NULL, 'TEXT', NULL, TRUE, FALSE, 4, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Applicant Identity', 'passport_expiry', 'Passport Expiry Date', NULL, 'DATE', NULL, TRUE, FALSE, 5, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Education', 'dli_name', 'Name of Designated Learning Institution (DLI)', NULL, 'TEXT', NULL, TRUE, FALSE, 6, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Education', 'program_name', 'Program Name', NULL, 'TEXT', NULL, TRUE, FALSE, 7, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Education', 'program_start_date', 'Program Start Date', NULL, 'DATE', NULL, TRUE, FALSE, 8, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Education', 'program_end_date', 'Program End Date', NULL, 'DATE', NULL, TRUE, FALSE, 9, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Education', 'level_of_study', 'Level of Study', NULL, 'SELECT', 'Certificate|Diploma|Bachelor|Master|PhD|K-12|Language|Other', TRUE, FALSE, 10, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Location', 'school_province', 'Province of School', NULL, 'SELECT', 'AB|BC|MB|NB|NL|NS|NT|NU|ON|PE|QC|SK|YT', TRUE, TRUE, 11, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Location', 'is_quebec', 'Is this a Quebec institution?', 'If yes, CAQ process applies instead of PAL/TAL', 'SELECT', 'Yes|No', TRUE, TRUE, 12, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'PAL/TAL/CAQ', 'has_pal_tal', 'Has the school issued a PAL/TAL?', NULL, 'SELECT', 'Yes|No|Not Sure', FALSE, TRUE, 13, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'PAL/TAL/CAQ', 'has_caq', 'Has the school issued a CAQ? (Quebec only)', NULL, 'SELECT', 'Yes|No|Not Applicable', FALSE, TRUE, 14, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Finances', 'funding_source', 'Who pays tuition and living expenses?', NULL, 'SELECT', 'Self|Parent/Family|Sponsor|Scholarship|Employer|GIC|Combination', TRUE, TRUE, 15, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Finances', 'funds_available', 'Approximate funds available (CAD)', NULL, 'TEXT', NULL, TRUE, FALSE, 16, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Finances', 'has_gic', 'Do you have a GIC?', NULL, 'SELECT', 'Yes|No', FALSE, FALSE, 17, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Sponsor', 'has_sponsor', 'Is a sponsor providing financial support?', NULL, 'SELECT', 'Yes|No', FALSE, TRUE, 18, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Sponsor', 'sponsor_relationship', 'Relationship to Sponsor', NULL, 'TEXT', NULL, FALSE, FALSE, 19, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Sponsor', 'sponsor_income_source', 'Sponsor''s Source of Income', NULL, 'TEXT', NULL, FALSE, FALSE, 20, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'History', 'prior_refusals', 'Have you had any prior visa/permit refusals?', NULL, 'SELECT', 'Yes|No', TRUE, TRUE, 21, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'History', 'prior_refusal_details', 'If yes, provide details', NULL, 'TEXTAREA', NULL, FALSE, FALSE, 22, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'History', 'prior_overstays', 'Have you ever overstayed a visa?', NULL, 'SELECT', 'Yes|No', TRUE, FALSE, 23, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'History', 'previous_canadian_apps', 'Any previous Canadian immigration applications?', NULL, 'SELECT', 'Yes|No', TRUE, FALSE, 24, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Family', 'spouse_accompanying', 'Is your spouse/partner accompanying you?', NULL, 'SELECT', 'Yes|No|Not Applicable', FALSE, TRUE, 25, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Family', 'children_accompanying', 'Are children accompanying you?', NULL, 'SELECT', 'Yes|No|Not Applicable', FALSE, TRUE, 26, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'Country-Specific', 'applying_from_country', 'Which country are you applying from?', NULL, 'TEXT', NULL, TRUE, TRUE, 27, CURRENT_TIMESTAMP);

-- ---- Visitor Visa ----
INSERT INTO intake_question_templates (id, service_type, section_name, question_key, question_label, help_text, input_type, options, required, is_trigger_question, sort_order, created_at) VALUES
(gen_random_uuid(), 'VISITOR_VISA', 'Visit Purpose', 'visit_purpose', 'Purpose of Visit', NULL, 'SELECT', 'Tourism|Family Visit|Business|Event|Medical|Other', TRUE, TRUE, 1, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'Visit Purpose', 'visit_purpose_details', 'Details of Visit Purpose', NULL, 'TEXTAREA', NULL, FALSE, FALSE, 2, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'Host', 'has_canadian_host', 'Is there a Canadian host?', NULL, 'SELECT', 'Yes|No', TRUE, TRUE, 3, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'Host', 'host_relationship', 'Relationship to Host', NULL, 'TEXT', NULL, FALSE, FALSE, 4, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'Host', 'host_name', 'Host Full Name', NULL, 'TEXT', NULL, FALSE, FALSE, 5, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'Host', 'host_status', 'Host''s Immigration Status', NULL, 'SELECT', 'Citizen|Permanent Resident|Temporary Resident|Other', FALSE, FALSE, 6, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'Duration', 'planned_arrival', 'Planned Arrival Date', NULL, 'DATE', NULL, TRUE, FALSE, 7, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'Duration', 'planned_departure', 'Planned Departure Date', NULL, 'DATE', NULL, TRUE, FALSE, 8, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'Funding', 'funding_type', 'Who is funding the trip?', NULL, 'SELECT', 'Self-funded|Host-funded|Employer|Combination', TRUE, TRUE, 9, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'Employment', 'current_employer', 'Current Employer', NULL, 'TEXT', NULL, FALSE, FALSE, 10, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'Employment', 'job_title', 'Job Title', NULL, 'TEXT', NULL, FALSE, FALSE, 11, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'Employment', 'leave_approved', 'Has leave been approved?', NULL, 'SELECT', 'Yes|No|Not Applicable', FALSE, FALSE, 12, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'Assets/Ties', 'property_owned', 'Do you own property in your home country?', NULL, 'SELECT', 'Yes|No', FALSE, FALSE, 13, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'Assets/Ties', 'family_ties', 'Family members remaining in home country', NULL, 'TEXTAREA', NULL, FALSE, FALSE, 14, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'Assets/Ties', 'business_owned', 'Do you own a business?', NULL, 'SELECT', 'Yes|No', FALSE, FALSE, 15, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'Travel History', 'countries_visited', 'Countries visited in the last 10 years', NULL, 'TEXTAREA', NULL, FALSE, FALSE, 16, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'Travel History', 'prior_canadian_visits', 'Have you visited Canada before?', NULL, 'SELECT', 'Yes|No', FALSE, FALSE, 17, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'Refusals', 'prior_visa_refusals', 'Any previous visa refusals (any country)?', NULL, 'SELECT', 'Yes|No', TRUE, TRUE, 18, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'Refusals', 'refusal_details', 'If yes, provide details', NULL, 'TEXTAREA', NULL, FALSE, FALSE, 19, CURRENT_TIMESTAMP);

-- ---- Spousal Sponsorship ----
INSERT INTO intake_question_templates (id, service_type, section_name, question_key, question_label, help_text, input_type, options, required, is_trigger_question, sort_order, created_at) VALUES
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Sponsor', 'sponsor_status', 'Sponsor''s Immigration Status', NULL, 'SELECT', 'Canadian Citizen|Permanent Resident', TRUE, TRUE, 1, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Sponsor', 'sponsor_in_canada', 'Is sponsor currently living in Canada?', NULL, 'SELECT', 'Yes|No', TRUE, TRUE, 2, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Sponsor', 'sponsor_province', 'Sponsor''s Province of Residence', NULL, 'SELECT', 'AB|BC|MB|NB|NL|NS|NT|NU|ON|PE|QC|SK|YT|Outside Canada', TRUE, TRUE, 3, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Applicant', 'applicant_country', 'Applicant''s Country of Residence', NULL, 'TEXT', NULL, TRUE, FALSE, 4, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Applicant', 'applicant_current_status', 'Applicant''s Current Immigration Status', NULL, 'TEXT', NULL, TRUE, FALSE, 5, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Applicant', 'applicant_prior_marriages', 'Has applicant been previously married?', NULL, 'SELECT', 'Yes|No', TRUE, FALSE, 6, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Relationship Type', 'relationship_type', 'Relationship Type', NULL, 'SELECT', 'Married|Common-Law|Conjugal', TRUE, TRUE, 7, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Relationship Timeline', 'first_contact_date', 'Date of First Contact', NULL, 'DATE', NULL, TRUE, FALSE, 8, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Relationship Timeline', 'first_meeting_date', 'Date of First In-Person Meeting', NULL, 'DATE', NULL, TRUE, FALSE, 9, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Relationship Timeline', 'engagement_date', 'Engagement Date (if applicable)', NULL, 'DATE', NULL, FALSE, FALSE, 10, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Relationship Timeline', 'marriage_cohabitation_date', 'Marriage/Cohabitation Date', NULL, 'DATE', NULL, TRUE, FALSE, 11, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Cohabitation', 'shared_address', 'Do you share an address?', NULL, 'SELECT', 'Yes|No', TRUE, FALSE, 12, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Cohabitation', 'cohabitation_dates', 'Dates of Cohabitation', NULL, 'TEXT', NULL, FALSE, FALSE, 13, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Cohabitation', 'cohabitation_proof', 'What cohabitation proof is available?', NULL, 'TEXTAREA', NULL, FALSE, FALSE, 14, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Dependents', 'has_children', 'Are there any children?', NULL, 'SELECT', 'Yes|No', TRUE, TRUE, 15, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Dependents', 'custody_issues', 'Any custody issues?', NULL, 'SELECT', 'Yes|No|Not Applicable', FALSE, FALSE, 16, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Previous Sponsorship', 'sponsor_previously_sponsored', 'Has the sponsor sponsored before?', NULL, 'SELECT', 'Yes|No', TRUE, TRUE, 17, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Criminal/Immigration History', 'prior_refusals_removals', 'Any prior refusals, removals, or criminality?', NULL, 'SELECT', 'Yes|No', TRUE, TRUE, 18, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Criminal/Immigration History', 'refusal_details', 'If yes, provide details', NULL, 'TEXTAREA', NULL, FALSE, FALSE, 19, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'Quebec', 'sponsor_in_quebec', 'Does the sponsor live in Quebec?', 'Quebec has a separate sponsorship process', 'SELECT', 'Yes|No', TRUE, TRUE, 20, CURRENT_TIMESTAMP);

-- ---- Express Entry ----
INSERT INTO intake_question_templates (id, service_type, section_name, question_key, question_label, help_text, input_type, options, required, is_trigger_question, sort_order, created_at) VALUES
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Program Path', 'program_path', 'Which Express Entry program?', NULL, 'SELECT', 'Federal Skilled Worker (FSW)|Canadian Experience Class (CEC)|Federal Skilled Trades (FST)|PNP Express Entry', TRUE, TRUE, 1, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Work History', 'current_employer', 'Current/Most Recent Employer', NULL, 'TEXT', NULL, TRUE, FALSE, 2, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Work History', 'job_title', 'Job Title', NULL, 'TEXT', NULL, TRUE, FALSE, 3, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Work History', 'noc_teer', 'NOC/TEER Code (if known)', NULL, 'TEXT', NULL, FALSE, FALSE, 4, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Work History', 'employment_dates', 'Employment Start and End Dates', NULL, 'TEXT', NULL, TRUE, FALSE, 5, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Work History', 'hours_per_week', 'Hours Per Week', NULL, 'TEXT', NULL, TRUE, FALSE, 6, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Work History', 'job_duties', 'Main Job Duties', NULL, 'TEXTAREA', NULL, TRUE, FALSE, 7, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Education', 'education_canadian_or_foreign', 'Is your highest education Canadian or Foreign?', NULL, 'SELECT', 'Canadian|Foreign|Both', TRUE, TRUE, 8, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Education', 'eca_completed', 'Has an Educational Credential Assessment (ECA) been completed?', NULL, 'SELECT', 'Yes|No|Not Applicable', TRUE, TRUE, 9, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Education', 'highest_education', 'Highest Level of Education', NULL, 'SELECT', 'High School|1-Year Post-Secondary|2-Year Post-Secondary|3-Year Post-Secondary|Bachelor|Two or More Degrees|Master|PhD', TRUE, FALSE, 10, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Language', 'language_test_type', 'Language Test Type', NULL, 'SELECT', 'IELTS|CELPIP|TEF|TCF|None Yet', TRUE, TRUE, 11, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Language', 'language_test_date', 'Test Date', NULL, 'DATE', NULL, FALSE, FALSE, 12, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Language', 'language_scores', 'Test Scores (L/R/W/S)', NULL, 'TEXT', NULL, FALSE, FALSE, 13, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Marital Status', 'marital_status', 'Marital Status', NULL, 'SELECT', 'Single|Married|Common-Law|Separated|Divorced|Widowed', TRUE, TRUE, 14, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Marital Status', 'spouse_accompanying', 'Is spouse/partner accompanying?', NULL, 'SELECT', 'Yes|No|Not Applicable', FALSE, TRUE, 15, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Dependents', 'has_dependents', 'Any dependent children?', NULL, 'SELECT', 'Yes|No', TRUE, TRUE, 16, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Dependents', 'custody_issues', 'Any custody issues?', NULL, 'SELECT', 'Yes|No|Not Applicable', FALSE, FALSE, 17, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Funds', 'funds_required', 'Are proof of funds required or exempt?', NULL, 'SELECT', 'Required|Exempt (have valid job offer)|Not Sure', TRUE, TRUE, 18, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Travel/Residence', 'countries_lived_in', 'Countries lived in for 6+ months since age 18', 'Used to determine police certificate requirements', 'TEXTAREA', NULL, TRUE, TRUE, 19, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Prior Applications', 'prior_refusals', 'Any prior Canadian refusals, inadmissibility, or misrepresentation?', NULL, 'SELECT', 'Yes|No', TRUE, TRUE, 20, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'Prior Applications', 'prior_refusal_details', 'If yes, provide details', NULL, 'TEXTAREA', NULL, FALSE, FALSE, 21, CURRENT_TIMESTAMP);

-- ---- Work Permit ----
INSERT INTO intake_question_templates (id, service_type, section_name, question_key, question_label, help_text, input_type, options, required, is_trigger_question, sort_order, created_at) VALUES
(gen_random_uuid(), 'WORK_PERMIT', 'Application Location', 'application_location', 'Where are you applying from?', NULL, 'SELECT', 'Inside Canada|Outside Canada|Port of Entry', TRUE, TRUE, 1, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'Work Permit Type', 'wp_type', 'Type of Work Permit', NULL, 'SELECT', 'Employer-Specific|Open Work Permit', TRUE, TRUE, 2, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'LMIA', 'lmia_status', 'LMIA Status', NULL, 'SELECT', 'LMIA Required (has LMIA)|LMIA Exempt|Unknown/Not Sure', TRUE, TRUE, 3, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'LMIA', 'lmia_number', 'LMIA Number (if applicable)', NULL, 'TEXT', NULL, FALSE, FALSE, 4, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'Employer', 'employer_name', 'Employer Legal Name', NULL, 'TEXT', NULL, TRUE, FALSE, 5, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'Employer', 'employer_cra_bn', 'Employer CRA Business Number', NULL, 'TEXT', NULL, FALSE, FALSE, 6, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'Employer', 'employer_job_title', 'Job Title', NULL, 'TEXT', NULL, TRUE, FALSE, 7, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'Offer', 'wage', 'Offered Wage (hourly/annual)', NULL, 'TEXT', NULL, TRUE, FALSE, 8, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'Offer', 'work_location', 'Work Location (city, province)', NULL, 'TEXT', NULL, TRUE, FALSE, 9, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'Offer', 'job_duties', 'Job Duties', NULL, 'TEXTAREA', NULL, TRUE, FALSE, 10, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'Offer', 'noc_teer', 'NOC/TEER Code (if known)', NULL, 'TEXT', NULL, FALSE, FALSE, 11, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'Applicant Status', 'current_status_in_canada', 'Current Immigration Status in Canada', NULL, 'SELECT', 'Study Permit|Work Permit|Visitor Record|No Status|Not in Canada', FALSE, TRUE, 12, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'Applicant Status', 'status_expiry_date', 'Current Status Expiry Date', NULL, 'DATE', NULL, FALSE, FALSE, 13, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'Family', 'spouse_accompanying', 'Is spouse/partner accompanying?', NULL, 'SELECT', 'Yes|No|Not Applicable', FALSE, TRUE, 14, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'Family', 'children_accompanying', 'Are children accompanying?', NULL, 'SELECT', 'Yes|No|Not Applicable', FALSE, TRUE, 15, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'Qualifications', 'highest_education', 'Highest Level of Education', NULL, 'TEXT', NULL, FALSE, FALSE, 16, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'Qualifications', 'professional_licence', 'Any professional licence/certification?', NULL, 'TEXT', NULL, FALSE, FALSE, 17, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'Qualifications', 'years_experience', 'Years of Relevant Work Experience', NULL, 'TEXT', NULL, FALSE, FALSE, 18, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'Prior Refusals', 'prior_refusals', 'Any prior work permit or visa refusals?', NULL, 'SELECT', 'Yes|No', TRUE, TRUE, 19, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'Prior Refusals', 'refusal_details', 'If yes, provide details', NULL, 'TEXTAREA', NULL, FALSE, FALSE, 20, CURRENT_TIMESTAMP);

-- ---- LMIA ----
INSERT INTO intake_question_templates (id, service_type, section_name, question_key, question_label, help_text, input_type, options, required, is_trigger_question, sort_order, created_at) VALUES
(gen_random_uuid(), 'LMIA', 'Employer', 'employer_legal_name', 'Employer Legal Name', NULL, 'TEXT', NULL, TRUE, FALSE, 1, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Employer', 'employer_operating_name', 'Operating/Trade Name', NULL, 'TEXT', NULL, FALSE, FALSE, 2, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Employer', 'cra_bn', 'CRA Business Number', NULL, 'TEXT', NULL, TRUE, FALSE, 3, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Employer', 'payroll_account', 'CRA Payroll Account Number', NULL, 'TEXT', NULL, TRUE, FALSE, 4, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Business', 'industry', 'Industry/Sector', NULL, 'TEXT', NULL, TRUE, FALSE, 5, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Business', 'business_address', 'Business Address', NULL, 'TEXT', NULL, TRUE, FALSE, 6, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Business', 'num_employees', 'Number of Employees', NULL, 'TEXT', NULL, TRUE, FALSE, 7, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Business', 'revenue_proof_available', 'Is revenue/financial proof available?', NULL, 'SELECT', 'Yes|No', TRUE, FALSE, 8, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Job', 'job_title', 'Job Title', NULL, 'TEXT', NULL, TRUE, FALSE, 9, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Job', 'wage', 'Offered Wage', NULL, 'TEXT', NULL, TRUE, FALSE, 10, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Job', 'hours_per_week', 'Hours Per Week', NULL, 'TEXT', NULL, TRUE, FALSE, 11, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Job', 'work_location', 'Work Location', NULL, 'TEXT', NULL, TRUE, FALSE, 12, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Job', 'job_duties', 'Main Duties', NULL, 'TEXTAREA', NULL, TRUE, FALSE, 13, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Job', 'noc_teer', 'NOC/TEER Code (if known)', NULL, 'TEXT', NULL, FALSE, FALSE, 14, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Stream', 'lmia_stream', 'LMIA Stream', NULL, 'SELECT', 'High-Wage|Low-Wage|PR Support|Global Talent Stream|Agricultural|Caregiver|Seasonal', TRUE, TRUE, 15, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Recruitment', 'where_advertised', 'Where were job ads posted?', NULL, 'TEXTAREA', NULL, TRUE, FALSE, 16, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Recruitment', 'ad_start_date', 'Job Ad Start Date', NULL, 'DATE', NULL, TRUE, FALSE, 17, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Recruitment', 'ad_end_date', 'Job Ad End Date', NULL, 'DATE', NULL, TRUE, FALSE, 18, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Recruitment', 'num_applicants', 'Number of Applicants Received', NULL, 'TEXT', NULL, FALSE, FALSE, 19, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Recruitment', 'num_interviewed', 'Number of Applicants Interviewed', NULL, 'TEXT', NULL, FALSE, FALSE, 20, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Candidate', 'candidate_name', 'Candidate Full Name', NULL, 'TEXT', NULL, TRUE, FALSE, 21, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Candidate', 'candidate_qualifications', 'Candidate Qualifications', NULL, 'TEXTAREA', NULL, FALSE, FALSE, 22, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Candidate', 'candidate_experience', 'Candidate Relevant Experience', NULL, 'TEXTAREA', NULL, FALSE, FALSE, 23, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Compliance', 'prior_lmia_history', 'Any prior LMIA applications?', NULL, 'SELECT', 'Yes|No', TRUE, TRUE, 24, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Compliance', 'prior_inspections', 'Any prior ESDC inspections?', NULL, 'SELECT', 'Yes|No', FALSE, FALSE, 25, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'Compliance', 'recent_layoffs', 'Any recent layoffs for this position?', NULL, 'SELECT', 'Yes|No', TRUE, TRUE, 26, CURRENT_TIMESTAMP);

-- ---- Citizenship ----
INSERT INTO intake_question_templates (id, service_type, section_name, question_key, question_label, help_text, input_type, options, required, is_trigger_question, sort_order, created_at) VALUES
(gen_random_uuid(), 'CITIZENSHIP', 'Age', 'applicant_age_category', 'Is the applicant an adult or minor?', NULL, 'SELECT', 'Adult (18+)|Minor (under 18)', TRUE, TRUE, 1, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'CITIZENSHIP', 'PR Date', 'pr_date', 'Date Became Permanent Resident', NULL, 'DATE', NULL, TRUE, FALSE, 2, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'CITIZENSHIP', 'Absences', 'absences_outside_canada', 'Have you travelled outside Canada during the eligibility period?', NULL, 'SELECT', 'Yes|No', TRUE, TRUE, 3, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'CITIZENSHIP', 'Absences', 'absence_details', 'If yes, list all trips (country, dates)', NULL, 'TEXTAREA', NULL, FALSE, FALSE, 4, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'CITIZENSHIP', 'Tax Years', 'tax_years_filed', 'For which years have you filed Canadian taxes?', NULL, 'TEXT', NULL, TRUE, FALSE, 5, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'CITIZENSHIP', 'Tax Years', 'missing_tax_years', 'Are there any missing tax filing years?', NULL, 'SELECT', 'Yes|No|Not Sure', FALSE, TRUE, 6, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'CITIZENSHIP', 'Language', 'language_proof_available', 'Is language proof available?', 'Required for applicants 18-54 at time of signing', 'SELECT', 'Yes|No|Exempt (age)', TRUE, TRUE, 7, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'CITIZENSHIP', 'Language', 'language_test_type', 'Language Test/Proof Type', NULL, 'TEXT', NULL, FALSE, FALSE, 8, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'CITIZENSHIP', 'Prohibitions', 'criminality', 'Any criminal charges, convictions, or ongoing proceedings?', NULL, 'SELECT', 'Yes|No', TRUE, TRUE, 9, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'CITIZENSHIP', 'Prohibitions', 'removal_order', 'Any removal orders?', NULL, 'SELECT', 'Yes|No', TRUE, TRUE, 10, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'CITIZENSHIP', 'Prohibitions', 'probation', 'Currently on probation?', NULL, 'SELECT', 'Yes|No', TRUE, FALSE, 11, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'CITIZENSHIP', 'Identity', 'available_ids', 'What identification documents are available?', NULL, 'TEXTAREA', NULL, TRUE, FALSE, 12, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'CITIZENSHIP', 'Identity', 'name_consistency', 'Is your name consistent across all documents?', NULL, 'SELECT', 'Yes|No', TRUE, TRUE, 13, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'CITIZENSHIP', 'Past Applications', 'prior_citizenship_app', 'Any prior citizenship application?', NULL, 'SELECT', 'Yes|No', TRUE, TRUE, 14, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'CITIZENSHIP', 'Past Applications', 'prior_app_details', 'If yes, provide details', NULL, 'TEXTAREA', NULL, FALSE, FALSE, 15, CURRENT_TIMESTAMP);

-- ---- PR Card / PRTD ----
INSERT INTO intake_question_templates (id, service_type, section_name, question_key, question_label, help_text, input_type, options, required, is_trigger_question, sort_order, created_at) VALUES
(gen_random_uuid(), 'PR_CARD_PRTD', 'Application Reason', 'application_reason', 'Reason for Application', NULL, 'SELECT', 'Renewal|Replacement|First Card|PR Travel Document (PRTD)', TRUE, TRUE, 1, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PR_CARD_PRTD', 'Card Expiry', 'pr_card_expiry', 'Current PR Card Expiry Date', NULL, 'DATE', NULL, FALSE, FALSE, 2, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PR_CARD_PRTD', 'Travel', 'days_outside_canada', 'Approximate days outside Canada in last 5 years', NULL, 'TEXT', NULL, TRUE, TRUE, 3, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PR_CARD_PRTD', 'Travel', 'travel_details', 'List all trips outside Canada (country, dates)', NULL, 'TEXTAREA', NULL, FALSE, FALSE, 4, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PR_CARD_PRTD', 'Lost/Damaged', 'card_lost_stolen_damaged', 'Was the card lost, stolen, or damaged?', NULL, 'SELECT', 'Lost|Stolen|Damaged|Not Applicable', FALSE, TRUE, 5, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PR_CARD_PRTD', 'Lost/Damaged', 'police_report_number', 'Police Report/Incident Number (if applicable)', NULL, 'TEXT', NULL, FALSE, FALSE, 6, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PR_CARD_PRTD', 'Urgency', 'urgent_processing', 'Do you need urgent processing?', NULL, 'SELECT', 'Yes|No', FALSE, FALSE, 7, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PR_CARD_PRTD', 'Urgency', 'urgency_reason', 'If yes, explain the urgency', NULL, 'TEXTAREA', NULL, FALSE, FALSE, 8, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PR_CARD_PRTD', 'Name Changes', 'name_gender_changes', 'Any legal name or gender changes since PR was granted?', NULL, 'SELECT', 'Yes|No', TRUE, TRUE, 9, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PR_CARD_PRTD', 'Name Changes', 'change_details', 'If yes, provide details', NULL, 'TEXTAREA', NULL, FALSE, FALSE, 10, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PR_CARD_PRTD', 'Documents', 'copr_available', 'Is your COPR (Confirmation of PR) available?', NULL, 'SELECT', 'Yes|No', TRUE, FALSE, 11, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PR_CARD_PRTD', 'Documents', 'record_of_landing_available', 'Is your Record of Landing available?', NULL, 'SELECT', 'Yes|No|Not Sure', FALSE, FALSE, 12, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PR_CARD_PRTD', 'Documents', 'passport_available', 'Is your current passport available?', NULL, 'SELECT', 'Yes|No', TRUE, FALSE, 13, CURRENT_TIMESTAMP);

-- ---- PGWP ----
INSERT INTO intake_question_templates (id, service_type, section_name, question_key, question_label, help_text, input_type, options, required, is_trigger_question, sort_order, created_at) VALUES
(gen_random_uuid(), 'PGWP', 'Graduation', 'completion_date', 'Program Completion Date', NULL, 'DATE', NULL, TRUE, FALSE, 1, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PGWP', 'Graduation', 'transcript_available', 'Is your final transcript available?', NULL, 'SELECT', 'Yes|No|Pending', TRUE, TRUE, 2, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PGWP', 'Graduation', 'completion_letter_available', 'Is your completion/graduation letter available?', NULL, 'SELECT', 'Yes|No|Pending', TRUE, TRUE, 3, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PGWP', 'School', 'dli_name', 'Designated Learning Institution Name', NULL, 'TEXT', NULL, TRUE, FALSE, 4, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PGWP', 'School', 'program_length', 'Program Length (months)', NULL, 'TEXT', NULL, TRUE, FALSE, 5, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PGWP', 'School', 'program_level', 'Program Level', NULL, 'SELECT', 'Certificate|Diploma|Associate|Bachelor|Master|PhD', TRUE, FALSE, 6, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PGWP', 'Status', 'study_permit_expiry', 'Study Permit Expiry Date', NULL, 'DATE', NULL, TRUE, TRUE, 7, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PGWP', 'Status', 'current_status', 'Current Immigration Status', NULL, 'SELECT', 'Valid Study Permit|Implied Status|Visitor Record|Other', TRUE, TRUE, 8, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PGWP', 'Language', 'language_test_taken', 'Have you taken a language test?', 'Required for some PGWP applications', 'SELECT', 'Yes|No|Exempt', TRUE, TRUE, 9, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PGWP', 'Language', 'language_test_date', 'Language Test Date', NULL, 'DATE', NULL, FALSE, FALSE, 10, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PGWP', 'Language', 'language_scores', 'Language Test Scores', NULL, 'TEXT', NULL, FALSE, FALSE, 11, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PGWP', 'Study History', 'full_time_all_terms', 'Were all terms full-time?', NULL, 'SELECT', 'Yes|No', TRUE, TRUE, 12, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PGWP', 'Study History', 'authorized_leaves', 'Any authorized leaves or part-time terms?', NULL, 'SELECT', 'Yes|No', FALSE, FALSE, 13, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PGWP', 'Study History', 'program_transfers', 'Any program or school transfers?', NULL, 'SELECT', 'Yes|No', FALSE, TRUE, 14, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PGWP', 'Passport', 'passport_expiry', 'Passport Expiry Date', NULL, 'DATE', NULL, TRUE, TRUE, 15, CURRENT_TIMESTAMP);

-- ---- Super Visa ----
INSERT INTO intake_question_templates (id, service_type, section_name, question_key, question_label, help_text, input_type, options, required, is_trigger_question, sort_order, created_at) VALUES
(gen_random_uuid(), 'SUPER_VISA', 'Applicant', 'applicant_name', 'Applicant Full Name', NULL, 'TEXT', NULL, TRUE, FALSE, 1, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SUPER_VISA', 'Applicant', 'applicant_relationship', 'Relationship to Host', NULL, 'SELECT', 'Parent|Grandparent', TRUE, TRUE, 2, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SUPER_VISA', 'Applicant', 'applicant_passport_expiry', 'Passport Expiry Date', NULL, 'DATE', NULL, TRUE, FALSE, 3, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SUPER_VISA', 'Applicant', 'applicant_country_residence', 'Country of Residence', NULL, 'TEXT', NULL, TRUE, FALSE, 4, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SUPER_VISA', 'Host', 'host_name', 'Host Full Name', NULL, 'TEXT', NULL, TRUE, FALSE, 5, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SUPER_VISA', 'Host', 'host_status', 'Host Immigration Status', NULL, 'SELECT', 'Canadian Citizen|Permanent Resident', TRUE, TRUE, 6, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SUPER_VISA', 'Host', 'host_relationship_proof', 'What proof of relationship is available?', NULL, 'TEXT', NULL, TRUE, FALSE, 7, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SUPER_VISA', 'Host', 'household_size', 'Total Household Size (including applicant)', NULL, 'TEXT', NULL, TRUE, FALSE, 8, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SUPER_VISA', 'Finances', 'host_income_docs_available', 'Are host income documents available (NOA, employment letter)?', NULL, 'SELECT', 'Yes|No|Partial', TRUE, TRUE, 9, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SUPER_VISA', 'Finances', 'host_support_evidence', 'What financial support evidence is available?', NULL, 'TEXTAREA', NULL, FALSE, FALSE, 10, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SUPER_VISA', 'Insurance', 'has_medical_insurance', 'Has qualifying medical insurance been obtained?', NULL, 'SELECT', 'Yes|No|In Progress', TRUE, TRUE, 11, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SUPER_VISA', 'Insurance', 'insurance_policy_details', 'Insurance Provider and Policy Number', NULL, 'TEXT', NULL, FALSE, FALSE, 12, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SUPER_VISA', 'Insurance', 'insurance_coverage_amount', 'Coverage Amount', NULL, 'TEXT', NULL, FALSE, FALSE, 13, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SUPER_VISA', 'Purpose/Duration', 'planned_arrival', 'Planned Arrival Date', NULL, 'DATE', NULL, FALSE, FALSE, 14, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SUPER_VISA', 'Purpose/Duration', 'planned_stay_location', 'Where in Canada will applicant stay?', NULL, 'TEXT', NULL, FALSE, FALSE, 15, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SUPER_VISA', 'History', 'prior_refusals', 'Any prior visa refusals?', NULL, 'SELECT', 'Yes|No', TRUE, TRUE, 16, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SUPER_VISA', 'History', 'refusal_details', 'If yes, provide details', NULL, 'TEXTAREA', NULL, FALSE, FALSE, 17, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SUPER_VISA', 'History', 'previous_travel_history', 'Previous travel history', NULL, 'TEXTAREA', NULL, FALSE, FALSE, 18, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SUPER_VISA', 'History', 'medical_concerns', 'Any medical concerns?', NULL, 'SELECT', 'Yes|No', FALSE, FALSE, 19, CURRENT_TIMESTAMP);

-- ======================== CONDITIONAL RULES ========================

-- Study Permit rules
INSERT INTO conditional_rules (id, service_type, trigger_question_key, trigger_value, operator, action_type, target_checklist_template_id, target_question_key, description, active, created_at) VALUES
(gen_random_uuid(), 'STUDY_PERMIT', 'is_quebec', 'Yes', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include CAQ requirement when school is in Quebec', TRUE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'school_province', 'QC', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include CAQ requirement when province is Quebec', TRUE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'has_sponsor', 'Yes', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include sponsor financial documents when sponsor is involved', TRUE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'spouse_accompanying', 'Yes', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include spouse/family documents when family is accompanying', TRUE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'children_accompanying', 'Yes', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include dependent children documents when children are accompanying', TRUE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'prior_refusals', 'Yes', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include prior refusal explanation letter when refusals exist', TRUE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'funding_source', 'Scholarship', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include scholarship award letter when scholarship-funded', TRUE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'STUDY_PERMIT', 'has_gic', 'Yes', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include GIC confirmation when GIC is available', TRUE, CURRENT_TIMESTAMP);

-- Visitor Visa rules
INSERT INTO conditional_rules (id, service_type, trigger_question_key, trigger_value, operator, action_type, target_checklist_template_id, target_question_key, description, active, created_at) VALUES
(gen_random_uuid(), 'VISITOR_VISA', 'has_canadian_host', 'Yes', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include invitation letter and host documents when host exists', TRUE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'visit_purpose', 'Business', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include business invitation/conference documents for business visits', TRUE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'prior_visa_refusals', 'Yes', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include refusal explanation when prior refusals exist', TRUE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'VISITOR_VISA', 'funding_type', 'Host-funded', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include host financial proof when host is funding trip', TRUE, CURRENT_TIMESTAMP);

-- Spousal Sponsorship rules
INSERT INTO conditional_rules (id, service_type, trigger_question_key, trigger_value, operator, action_type, target_checklist_template_id, target_question_key, description, active, created_at) VALUES
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'relationship_type', 'Common-Law', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include statutory declaration of common-law union', TRUE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'relationship_type', 'Conjugal', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include conjugal relationship evidence and barrier explanation', TRUE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'has_children', 'Yes', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include children''s identity/custody documents', TRUE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'sponsor_previously_sponsored', 'Yes', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include proof that 3-year undertaking from previous sponsorship has ended', TRUE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'sponsor_in_quebec', 'Yes', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include Quebec CSQ/undertaking forms for Quebec sponsorship', TRUE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SPOUSAL_SPONSORSHIP', 'prior_refusals_removals', 'Yes', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include rehabilitation/explanation for prior refusals or inadmissibility', TRUE, CURRENT_TIMESTAMP);

-- Express Entry rules
INSERT INTO conditional_rules (id, service_type, trigger_question_key, trigger_value, operator, action_type, target_checklist_template_id, target_question_key, description, active, created_at) VALUES
(gen_random_uuid(), 'EXPRESS_ENTRY', 'education_canadian_or_foreign', 'Foreign', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include ECA report for foreign education credentials', TRUE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'education_canadian_or_foreign', 'Both', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include ECA report when applicant has both Canadian and foreign education', TRUE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'has_dependents', 'Yes', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include dependent children documents', TRUE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'spouse_accompanying', 'Yes', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include spouse documents and language test', TRUE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'prior_refusals', 'Yes', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include prior refusal explanation letter', TRUE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'EXPRESS_ENTRY', 'program_path', 'PNP Express Entry', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include PNP nomination certificate', TRUE, CURRENT_TIMESTAMP);

-- Work Permit rules
INSERT INTO conditional_rules (id, service_type, trigger_question_key, trigger_value, operator, action_type, target_checklist_template_id, target_question_key, description, active, created_at) VALUES
(gen_random_uuid(), 'WORK_PERMIT', 'lmia_status', 'LMIA Required (has LMIA)', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include LMIA confirmation letter', TRUE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'wp_type', 'Open Work Permit', 'EQUALS', 'EXCLUDE', NULL, NULL, 'Exclude employer-specific documents for open work permits', TRUE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'spouse_accompanying', 'Yes', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include spouse/family documents', TRUE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'prior_refusals', 'Yes', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include prior refusal explanation letter', TRUE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'WORK_PERMIT', 'application_location', 'Inside Canada', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include current status documents for in-Canada applications', TRUE, CURRENT_TIMESTAMP);

-- LMIA rules
INSERT INTO conditional_rules (id, service_type, trigger_question_key, trigger_value, operator, action_type, target_checklist_template_id, target_question_key, description, active, created_at) VALUES
(gen_random_uuid(), 'LMIA', 'lmia_stream', 'Global Talent Stream', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include ESDC referral partner letter for Global Talent Stream', TRUE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'lmia_stream', 'Agricultural', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include seasonal agricultural worker program documents', TRUE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'lmia_stream', 'Caregiver', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include caregiver-specific employer requirements', TRUE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'LMIA', 'recent_layoffs', 'Yes', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include layoff justification when recent layoffs occurred', TRUE, CURRENT_TIMESTAMP);

-- Citizenship rules
INSERT INTO conditional_rules (id, service_type, trigger_question_key, trigger_value, operator, action_type, target_checklist_template_id, target_question_key, description, active, created_at) VALUES
(gen_random_uuid(), 'CITIZENSHIP', 'applicant_age_category', 'Minor (under 18)', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include parent/guardian documents for minor applicants', TRUE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'CITIZENSHIP', 'applicant_age_category', 'Minor (under 18)', 'EQUALS', 'EXCLUDE', NULL, NULL, 'Exclude language test for minor applicants', TRUE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'CITIZENSHIP', 'absences_outside_canada', 'Yes', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include absence log with proof of travel dates', TRUE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'CITIZENSHIP', 'criminality', 'Yes', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include court records and rehabilitation documents', TRUE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'CITIZENSHIP', 'name_consistency', 'No', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include legal name change certificates', TRUE, CURRENT_TIMESTAMP);

-- PR Card rules
INSERT INTO conditional_rules (id, service_type, trigger_question_key, trigger_value, operator, action_type, target_checklist_template_id, target_question_key, description, active, created_at) VALUES
(gen_random_uuid(), 'PR_CARD_PRTD', 'application_reason', 'PR Travel Document (PRTD)', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include PRTD-specific documents and proof of ties to Canada', TRUE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PR_CARD_PRTD', 'card_lost_stolen_damaged', 'Stolen', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include police report for stolen card', TRUE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PR_CARD_PRTD', 'name_gender_changes', 'Yes', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include legal name/gender change documents', TRUE, CURRENT_TIMESTAMP);

-- PGWP rules
INSERT INTO conditional_rules (id, service_type, trigger_question_key, trigger_value, operator, action_type, target_checklist_template_id, target_question_key, description, active, created_at) VALUES
(gen_random_uuid(), 'PGWP', 'transcript_available', 'Pending', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include interim transcript and expected date of final transcript', TRUE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PGWP', 'program_transfers', 'Yes', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include transfer letters from all institutions attended', TRUE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'PGWP', 'language_test_taken', 'No', 'EQUALS', 'INCLUDE', NULL, NULL, 'Flag: language test may be required depending on graduation date', TRUE, CURRENT_TIMESTAMP);

-- Super Visa rules
INSERT INTO conditional_rules (id, service_type, trigger_question_key, trigger_value, operator, action_type, target_checklist_template_id, target_question_key, description, active, created_at) VALUES
(gen_random_uuid(), 'SUPER_VISA', 'has_medical_insurance', 'No', 'EQUALS', 'INCLUDE', NULL, NULL, 'Flag: medical insurance is mandatory for Super Visa', TRUE, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'SUPER_VISA', 'prior_refusals', 'Yes', 'EQUALS', 'INCLUDE', NULL, NULL, 'Include prior refusal explanation letter', TRUE, CURRENT_TIMESTAMP);
