package com.immiauto.enums;

public enum CaseStatus {
    INTAKE_PENDING,
    INTAKE_COMPLETED,
    CHECKLIST_PENDING,
    DOCUMENTS_COLLECTING,
    DOCUMENTS_UNDER_REVIEW,
    FILE_READY,
    APPLICATION_PREP,
    FINAL_REVIEW,
    APPLICATION_SUBMITTED,
    POST_SUBMISSION,
    DECISION_RECEIVED,
    CLOSED
}
